/* eslint-disable no-console -- a CLI self-test script: its output IS the result. */
/**
 * F-C5 self-test — the MATURED bucket's wire decoding and the two-bucket refund
 * tax, asserted against vectors generated by the CONTRACT'S OWN functions.
 *
 * Run:
 *   cd apps/blog && npx tsx features/creator-tokens/lib/vsc/matured-decode.selftest.ts
 *
 * The vector table below is the verbatim output of
 *   cd creator-tokens && go test ./core/ -run TestFC5_WireVectors -v
 * which asserts each row against core/matured.go's u64ToLE / maturingGrossShare
 * and core/refund.go's tax path before printing it. Both sides assert the same
 * table, so a drift in either implementation fails one of the two.
 *
 * Why this exists: the audit recorded F-C5's client half as blocked on an
 * unknown — "the node's byte->string encoding is not in client code". It is in
 * go-vsc's resolver: the default encoding is a raw byte->string cast, which
 * corrupts non-UTF-8 bytes into U+FFFD before they reach us. Confirmed live on
 * mainnet, where the DEX pool's `r0` reads "#�c" by default and "239c63"
 * with encoding:"hex". Hence the hex read this file's decoder consumes.
 */

import { decodeMaturedLeHex } from './reads';
import { refundNetBaseUnits, maturingGrossShareBaseUnits } from '../contract-math';

interface Vector {
  tokens: number;
  hex: string;
  maturing: number;
  matured: number;
  reserve: number;
  supply: number;
  heldBlocks: number;
  gross: number;
  tax: number;
  net: number;
  taxBps: number;
}

const VECTORS: Vector[] = [
  { tokens: 1000, hex: '00', maturing: 1000, matured: 0, reserve: 500000, supply: 10000, heldBlocks: 0, gross: 50000, tax: 10000, net: 40000, taxBps: 2000 },
  { tokens: 1000, hex: 'e803', maturing: 0, matured: 1000, reserve: 500000, supply: 10000, heldBlocks: 0, gross: 50000, tax: 0, net: 50000, taxBps: 2000 },
  { tokens: 1000, hex: 'f401', maturing: 500, matured: 500, reserve: 500000, supply: 10000, heldBlocks: 0, gross: 50000, tax: 5000, net: 45000, taxBps: 2000 },
  { tokens: 1000, hex: 'fa', maturing: 750, matured: 250, reserve: 123457, supply: 9991, heldBlocks: 100, gross: 12356, tax: 1854, net: 10502, taxBps: 2000 },
  { tokens: 1000, hex: 'e703', maturing: 1, matured: 999, reserve: 999983, supply: 100003, heldBlocks: 0, gross: 9999, tax: 2, net: 9997, taxBps: 2000 },
  { tokens: 1000, hex: 'f401', maturing: 500, matured: 500, reserve: 500000, supply: 10000, heldBlocks: 1209600, gross: 50000, tax: 0, net: 50000, taxBps: 0 }
];

let failures = 0;
let checks = 0;

function check(name: string, condition: boolean, detail?: string): void {
  checks += 1;
  if (!condition) {
    failures += 1;
    console.error(`FAIL  ${name}${detail ? `\n      ${detail}` : ''}`);
  } else {
    console.log(`ok    ${name}`);
  }
}

// ── 1. The LE wire decoding, against the contract's own encoder output.
for (const v of VECTORS) {
  const got = decodeMaturedLeHex(v.hex);
  check(
    `decode ${v.hex || '(empty)'} -> ${v.matured}`,
    got === v.matured,
    got === v.matured ? undefined : `got ${got}, want ${v.matured}`
  );
}

// ── 2. Absent/empty is a real zero (setMatured DELETES at zero), but garbage
// is unavailable — never silently zero.
check('absent key decodes to 0', decodeMaturedLeHex(null) === 0);
check('empty string decodes to 0', decodeMaturedLeHex('') === 0);
check('undefined decodes to 0', decodeMaturedLeHex(undefined) === 0);
check('odd-length hex is unavailable (null)', decodeMaturedLeHex('abc') === null);
check('non-hex is unavailable (null)', decodeMaturedLeHex('zz') === null);
check('9 bytes is refused, matching leToU64', decodeMaturedLeHex('000000000000000000') === null);
check('8 bytes is accepted', decodeMaturedLeHex('0100000000000000') === 1);
// The U+FFFD case: what the DEFAULT encoding would have handed us. It must not
// decode to a plausible-looking number.
check('replacement-char payload is unavailable (null)', decodeMaturedLeHex('�xM') === null);

// ── 3. The two-bucket refund tax, against the contract's numbers.
for (const v of VECTORS) {
  const r = refundNetBaseUnits(v.reserve, v.tokens, v.supply, v.heldBlocks, v.maturing);
  const label = `refund m=${v.maturing}/t=${v.matured} held=${v.heldBlocks}`;
  check(`${label} gross`, r.grossBaseUnits === v.gross, `got ${r.grossBaseUnits}, want ${v.gross}`);
  check(`${label} tax`, r.taxBaseUnits === v.tax, `got ${r.taxBaseUnits}, want ${v.tax}`);
  check(`${label} net`, r.netBaseUnits === v.net, `got ${r.netBaseUnits}, want ${v.net}`);
  check(`${label} taxBps`, r.taxBps === v.taxBps, `got ${r.taxBps}, want ${v.taxBps}`);
}

// ── 4. The regression this fix is FOR: reading the maturing bucket alone.
// A holder who is 100% matured owes zero tax; the old code taxed them in full.
const oldWay = refundNetBaseUnits(500000, 1000, 10000, 0); // no maturing arg = all-maturing
const newWay = refundNetBaseUnits(500000, 1000, 10000, 0, 0); // fully matured
check('all-matured holder is untaxed under the fix', newWay.taxBaseUnits === 0);
check('the old all-maturing path is unchanged (back-compat)', oldWay.taxBaseUnits === 10000);
check('the fix actually changes the number', oldWay.netBaseUnits !== newWay.netBaseUnits);

// ── 5. Apportionment shortcuts, ported from maturingGrossShare.
check('share: zero maturing -> 0', maturingGrossShareBaseUnits(50000, 0, 1000) === 0);
check('share: all maturing -> full gross', maturingGrossShareBaseUnits(50000, 1000, 1000) === 50000);
check('share: rounds UP (ceil)', maturingGrossShareBaseUnits(9999, 1, 1000) === 10);
check('share: zero gross -> 0', maturingGrossShareBaseUnits(0, 500, 1000) === 0);

console.log(`\n${checks - failures}/${checks} checks passed`);
if (failures > 0) {
  console.error(`${failures} FAILED`);
  process.exit(1);
}
