/* eslint-disable no-console -- a CLI self-test script: its output IS the result. */
/**
 * F-C5 self-test — the MATURED bucket's wire decoding and the two-bucket refund
 * tax, asserted against vectors generated by the CONTRACT'S OWN functions.
 *
 * Run:
 *   cd apps/blog && npx tsx features/creator-tokens/lib/vsc/matured-decode.selftest.ts
 *
 * The vector table below is the verbatim output of
 *   cd creator-tokens && go test ./core/ -run TestFC5_WireVectors -v
 * which asserts each row against core/matured.go's u64ToLE / maturingGrossShare
 * and core/refund.go's tax path before printing it. Both sides assert the same
 * table, so a drift in either implementation fails one of the two.
 *
 * Why this exists: the audit recorded F-C5's client half as blocked on an
 * unknown — "the node's byte->string encoding is not in client code". It is in
 * go-vsc's resolver: the default encoding is a raw byte->string cast, which
 * corrupts non-UTF-8 bytes into U+FFFD before they reach us. Confirmed live on
 * mainnet, where the DEX pool's `r0` reads "#�c" by default and "239c63"
 * with encoding:"hex". Hence the hex read this file's decoder consumes.
 */

import { decodeMaturedLeHex, maturedTokensFromState } from './reads';
import { refundNetBaseUnits, maturingGrossShareBaseUnits, formatTokenAmountFixed, fromUnits } from '../contract-math';

interface Vector {
  tokens: number;
  tokensDecimal: string;
  hex: string;       // `bal|`: LE u64 of the matured WHOLE tokens
  fracUnits: number; // `balf|`: the 0..99-unit remainder, a decimal string on the wire
  maturing: number;
  matured: number;
  reserve: number;
  supply: number;
  heldBlocks: number;
  gross: number;
  tax: number;
  net: number;
  taxBps: number;
}

// v6 (2026-09-22): every count is in 0.01-token UNITS (core/testdata/fc5-vectors-v6.json,
// printed by `go test ./core/ -run TestFC5_WireVectors -v`); `tokensDecimal` is the
// wire's decimal token string for the same count. The refund maths is scale-free, so
// the six pre-v6 rows keep their figures and three fractional rows join them.
// The matured bucket is TWO keys: `hex` is what `bal|` holds (whole tokens, the
// integer magi-market reads, unchanged by v6) and `fracUnits` is `balf|`.
const VECTORS: Vector[] = [
  { tokens: 1000, tokensDecimal: '10.00', hex: '00', fracUnits: 0, maturing: 1000, matured: 0, reserve: 500000, supply: 10000, heldBlocks: 0, gross: 50000, tax: 7500, net: 42500, taxBps: 1500 },
  { tokens: 1000, tokensDecimal: '10.00', hex: '0a', fracUnits: 0, maturing: 0, matured: 1000, reserve: 500000, supply: 10000, heldBlocks: 0, gross: 50000, tax: 0, net: 50000, taxBps: 1500 },
  { tokens: 1000, tokensDecimal: '10.00', hex: '05', fracUnits: 0, maturing: 500, matured: 500, reserve: 500000, supply: 10000, heldBlocks: 0, gross: 50000, tax: 3750, net: 46250, taxBps: 1500 },
  { tokens: 1000, tokensDecimal: '10.00', hex: '02', fracUnits: 50, maturing: 750, matured: 250, reserve: 123457, supply: 9991, heldBlocks: 100, gross: 12356, tax: 1391, net: 10965, taxBps: 1500 },
  { tokens: 1000, tokensDecimal: '10.00', hex: '09', fracUnits: 99, maturing: 1, matured: 999, reserve: 999983, supply: 100003, heldBlocks: 0, gross: 9999, tax: 2, net: 9997, taxBps: 1500 },
  { tokens: 1000, tokensDecimal: '10.00', hex: '05', fracUnits: 0, maturing: 500, matured: 500, reserve: 500000, supply: 10000, heldBlocks: 1209600, gross: 50000, tax: 0, net: 50000, taxBps: 0 },
  { tokens: 150, tokensDecimal: '1.50', hex: '01', fracUnits: 13, maturing: 37, matured: 113, reserve: 500000, supply: 10000, heldBlocks: 0, gross: 7500, tax: 278, net: 7222, taxBps: 1500 },
  { tokens: 2, tokensDecimal: '0.02', hex: '00', fracUnits: 1, maturing: 1, matured: 1, reserve: 2023, supply: 200, heldBlocks: 0, gross: 20, tax: 2, net: 18, taxBps: 1500 },
  { tokens: 250, tokensDecimal: '2.50', hex: '00', fracUnits: 0, maturing: 250, matured: 0, reserve: 1007, supply: 250, heldBlocks: 100, gross: 1007, tax: 152, net: 855, taxBps: 1500 }
];

let failures = 0;
let checks = 0;

function check(name: string, condition: boolean, detail?: string): void {
  checks += 1;
  if (!condition) {
    failures += 1;
    console.error(`FAIL  ${name}${detail ? `\n      ${detail}` : ''}`);
  } else {
    console.log(`ok    ${name}`);
  }
}

// ── 1. The LE wire decoding, against the contract's own encoder output: the
// whole-token half decodes alone, and the two-key reader rebuilds the unit count.
for (const v of VECTORS) {
  const whole = decodeMaturedLeHex(v.hex);
  const wantWhole = Math.floor(v.matured / 100);
  check(
    `decode ${v.hex || '(empty)'} -> ${wantWhole} whole`,
    whole === wantWhole,
    whole === wantWhole ? undefined : `got ${whole}, want ${wantWhole}`
  );
  const tokens = maturedTokensFromState(v.hex, String(v.fracUnits));
  const units = tokens === null ? null : Math.round(tokens * 100);
  check(
    `bal| ${v.hex || '(empty)'} + balf| ${v.fracUnits} -> ${v.matured} units`,
    units === v.matured,
    units === v.matured ? undefined : `got ${units}, want ${v.matured}`
  );
}
check('two-key reader: absent balf| is a real zero remainder', maturedTokensFromState('03', null) === 3);
check('two-key reader: absent bal| with a remainder is below one token', maturedTokensFromState(null, '7') === 0.07);
check('two-key reader: undecodable bal| is unavailable, not zero', maturedTokensFromState('abc', '7') === null);

// ── 2. Absent/empty is a real zero (setMatured DELETES at zero), but garbage
// is unavailable — never silently zero.
check('absent key decodes to 0', decodeMaturedLeHex(null) === 0);
check('empty string decodes to 0', decodeMaturedLeHex('') === 0);
check('undefined decodes to 0', decodeMaturedLeHex(undefined) === 0);
check('odd-length hex is unavailable (null)', decodeMaturedLeHex('abc') === null);
check('non-hex is unavailable (null)', decodeMaturedLeHex('zz') === null);
check('9 bytes is refused, matching leToU64', decodeMaturedLeHex('000000000000000000') === null);
check('8 bytes is accepted', decodeMaturedLeHex('0100000000000000') === 1);
// The U+FFFD case: what the DEFAULT encoding would have handed us. It must not
// decode to a plausible-looking number.
check('replacement-char payload is unavailable (null)', decodeMaturedLeHex('�xM') === null);

// ── 3. The two-bucket refund tax, against the contract's numbers.
for (const v of VECTORS) {
  const r = refundNetBaseUnits(v.reserve, v.tokens, v.supply, v.heldBlocks, v.maturing);
  const label = `refund m=${v.maturing}/t=${v.matured} held=${v.heldBlocks}`;
  check(`${label} gross`, r.grossBaseUnits === v.gross, `got ${r.grossBaseUnits}, want ${v.gross}`);
  check(`${label} tax`, r.taxBaseUnits === v.tax, `got ${r.taxBaseUnits}, want ${v.tax}`);
  check(`${label} net`, r.netBaseUnits === v.net, `got ${r.netBaseUnits}, want ${v.net}`);
  check(`${label} taxBps`, r.taxBps === v.taxBps, `got ${r.taxBps}, want ${v.taxBps}`);
}

// ── 4. The regression this fix is FOR: reading the maturing bucket alone.
// A holder who is 100% matured owes zero tax; the old code taxed them in full.
const oldWay = refundNetBaseUnits(500000, 1000, 10000, 0); // no maturing arg = all-maturing
const newWay = refundNetBaseUnits(500000, 1000, 10000, 0, 0); // fully matured
check('all-matured holder is untaxed under the fix', newWay.taxBaseUnits === 0);
// ★ THE GOLDEN VECTORS ABOVE AND THIS FIGURE ARE AT MaxExitTaxBps = 1500.
// They were written at 2000 and were never revisited when params.go halved the
// trade fee and cut the exit-tax ceiling on 2026-09-09, so this file failed 12
// checks against correct code for three days. Recomputed 2026-09-12 from the
// same formula the contract uses: share = ceil(gross x maturing / tokens),
// tax = ceil(share x taxBps / 1e4), taxBps = ceil(1500 x (decay - held) / decay).
check('the old all-maturing path is unchanged (back-compat)', oldWay.taxBaseUnits === 7500);
check('the fix actually changes the number', oldWay.netBaseUnits !== newWay.netBaseUnits);

// ── 5. Apportionment shortcuts, ported from maturingGrossShare.
check('share: zero maturing -> 0', maturingGrossShareBaseUnits(50000, 0, 1000) === 0);
check('share: all maturing -> full gross', maturingGrossShareBaseUnits(50000, 1000, 1000) === 50000);
check('share: rounds UP (ceil)', maturingGrossShareBaseUnits(9999, 1, 1000) === 10);
check('share: zero gross -> 0', maturingGrossShareBaseUnits(0, 500, 1000) === 0);

for (const v of VECTORS) {
  check(`v6 wire: ${v.tokens} units prints as "${v.tokensDecimal}"`, formatTokenAmountFixed(fromUnits(v.tokens)) === v.tokensDecimal, `got ${formatTokenAmountFixed(fromUnits(v.tokens))}`);
}

console.log(`\n${checks - failures}/${checks} checks passed`);
if (failures > 0) {
  console.error(`${failures} FAILED`);
  process.exit(1);
}
