package core

import (
	"fmt"
	"math/big"
	"math/rand"
	"sort"
	"strings"
	"testing"
)

// ===========================================================================
// fuzz_test.go — randomized property suite over the WHOLE core contract
// surface (API.md): register/renew/buy/sell/claimTradeFees/ask/answer/
// reclaim/transfer/refund/refundHolder/setFace/setCap/closeIfDrained/
// recordObs/askRate, across several markets and holders, with random
// amounts and random block advances.
//
// PORTED OFF THE PAR MINT (2026-07-21, this rewrite): the issuance path is
// Buy on the curve — Prepay is DELETED with its mechanism (an unbounded
// mint-cheap/redeem-dear loop against the curve; transfer.go's header has
// the autopsy) — and the suite's old load-bearing invariant, the PAR PEG
// (reserve == supply exactly), is replaced by the CURVE invariant below.
// Sell and ClaimTradeFees join the action mix; TransferCredits carries its
// RULING-A `block` parameter.
//
// OWNERSHIP: this file only. Every helper below is prefixed `fz` — five
// other authors already have helpers in this package (setupMarket,
// sumBalances, errSymbol, forceFrozen, activateMarket, mustRegister, ...)
// and nothing here may collide with any of them.
//
// DECORRELATION: the scripted end-to-end harness (harness_test.go) follows
// storylines; nothing here does — every sequence is generated by math/rand
// from a fixed seed, every parameter choice is adversarial (boundary-
// biased, not "plausible"), and failures print the seed plus the full step
// trace so they are exactly replayable.
//
// -----------------------------------------------------------------------
// THE CURVE INVARIANT (replaces the PAR peg — read before the checks).
//
// Through the public API alone, for every creator:
//
//	reserve(c) >= area(supply(c))  ALWAYS, and
//	reserve(c) == area(supply(c))  EXACTLY until the market's first
//	                               wind-down refund of its current
//	                               incarnation.
//
// Why the equality (RULING A/I): Buy adds exactly the area step
// area(S+n) − area(S); Sell removes exactly area(S) − area(S−ΔS); no other
// function touches kReserve; induction from the S=0, R=0 genesis.
//
// Why wind-down flips it to >=: Refund/RefundHolder pay the flat pro-rata
// floor(R·c/S), which is <= the marginal area step the burn un-backs
// (average <= marginal on a rising curve), so each refund leaves
// R' >= area(S') — the floor dust flows FORWARD to later claimants
// (refund.go C-22), never out. Buys are structurally dead in FROZEN/CLOSED
// (RequireInflowOpen), so the surplus is not buyable — and C-24 proves the
// LAST refund drains R to exactly 0, so a re-registered incarnation starts
// back at equality. The walk tracks "has this incarnation refunded yet"
// per creator and asserts the equality form whenever it can.
//
// Rounding property #4 under the curve: the ONE rounding site is area's
// floor (curve.go); trade totals are exact area steps (equalities L1-L5,
// asserted per-op in curve_fuzz_test.go); refund rounding favours the
// remaining holders (C-22). The places rounding is genuinely live remain
// credits-per-ask (ceilDiv(face,rate)) and twap.go's floor — both fuzzed
// independently below, unchanged.
// ===========================================================================

// ---------------------------------------------------------------------------
// fz harness: accounts, world, generic helpers.
// ---------------------------------------------------------------------------

var fzCreators = []string{"fzcreator1", "fzcreator2", "fzcreator3", "fzcreator4"}

// fzHolders deliberately includes two of the creators acting as ordinary
// holders in OTHER creators' markets (a creator-as-holder cross-over), on
// top of the dedicated pure-holder accounts.
var fzHolders = []string{
	"fzholder1", "fzholder2", "fzholder3", "fzholder4", "fzholder5", "fzholder6",
	"fzcreator1", "fzcreator2",
}

var fzAllActors = func() []string {
	seen := map[string]bool{}
	var out []string
	for _, a := range append(append([]string{}, fzCreators...), fzHolders...) {
		if !seen[a] {
			seen[a] = true
			out = append(out, a)
		}
	}
	sort.Strings(out)
	return out
}()

// fzCeilDiv independently computes ceil(a/b) for a>=0, b>0 WITHOUT calling
// creditsForAsk or mMulDivCeil — an independent model to check the real
// implementation against, not a tautological self-check.
func fzCeilDiv(a, b *big.Int) *big.Int {
	q, r := new(big.Int).QuoRem(a, b, new(big.Int))
	if r.Sign() != 0 {
		q.Add(q, big.NewInt(1))
	}
	return q
}

func fzBigToInt64Safe(b *big.Int) int64 {
	if b.IsInt64() {
		return b.Int64()
	}
	if b.Sign() < 0 {
		return -1
	}
	return int64(1) << 60
}

// fzOrderInvariantDump is fzCanonicalDump minus the two key families that
// are ORDER-DEPENDENT BY DESIGN under the curve, and money-invariant in
// aggregate. Both exclusions are justified here and both are replaced by an
// explicit AGGREGATE assertion (fzAssertOrderInvariantAggregates), so
// nothing is merely waved away:
//
//	"bas|"  — the per-holder cost basis (RULING J1). Basis is AVERAGE-COST:
//	          a transfer that happens BEFORE a buy moves a different
//	          proportional share than the same transfer AFTER it, because
//	          the average it is a share OF has changed. Those are two
//	          genuinely different acquisition histories, not two orderings
//	          of one. Measured on the exact counterexample this test found
//	          (buy 54 / buy 196 / transfer 27, one block): the per-holder
//	          split differs, and Σ basis is IDENTICAL to the unit
//	          (1,889,234 either way) — which is the property that actually
//	          matters and which is asserted below.
//	"acq|"  — the per-holder hold clock, for the same reason one level up:
//	          it is a SIZE-WEIGHTED AVERAGE of acquisition blocks, so it
//	          encodes the history, and reordering the history changes it.
//	          It sets the tax RATE only; it holds no money.
//
// Everything that holds money — kReserve, kSupply, every kBal, the escrow
// records, the TWAP ring, and the SUM of the two fee pots — stays in the
// compared dump and must match byte-for-byte.
//
// DISCLOSED, not fixed (the honest residual): the creator/platform SPLIT of
// a trade fee can differ by ONE base unit across permutations, because the
// split floors per trade (floor(fee/2), odd unit → platform, tradefee.go)
// and reordering changes which trade carries which cost. The TOTAL fee is
// invariant; only the 1-unit parity moves, and it moves between two
// protocol-side pots, never to or from a user. That is why the aggregate
// assertion below compares kFeeBal + kTreasury as a SUM rather than
// separately.
func fzOrderInvariantDump(s *MemStore) string {
	keys := s.Keys()
	sort.Strings(keys)
	var b strings.Builder
	for _, k := range keys {
		if strings.HasPrefix(k, "bas|") || strings.HasPrefix(k, "acq|") ||
			strings.HasPrefix(k, "fee|") || k == "treasury" {
			continue
		}
		v, _ := s.Get(k)
		if v == "" {
			continue
		}
		b.WriteString(k)
		b.WriteString("=")
		b.WriteString(v)
		b.WriteString("\n")
	}
	return b.String()
}

// fzOrderAggregates returns the money aggregates that MUST be identical
// across every permutation of the same successful op set: Σ basis (per
// creator), and Σ (all fee pots + treasury) — the two quantities whose
// per-key distribution is legitimately order-dependent.
func fzOrderAggregates(s *MemStore) string {
	total := big.NewInt(0)
	for _, k := range s.Keys() {
		if strings.HasPrefix(k, "bas|") {
			total = mAdd(total, getMoney(s, k))
		}
	}
	pots := getMoney(s, kTreasury())
	for _, a := range fzAllActors {
		pots = mAdd(pots, getMoney(s, kFeeBal(a)))
	}
	return "Sbasis=" + total.String() + " Spots=" + pots.String()
}

// fzCanonicalDump renders every non-empty key/value in s, sorted, as one
// string — used to compare final states across permutations byte-for-byte.
// MemStore.Keys() ranges a Go map (randomized iteration order per process),
// so the sort is what makes this comparison meaningful at all.
func fzCanonicalDump(s *MemStore) string {
	keys := s.Keys()
	sort.Strings(keys)
	var b strings.Builder
	for _, k := range keys {
		v, _ := s.Get(k)
		if v == "" {
			continue
		}
		b.WriteString(k)
		b.WriteByte('=')
		b.WriteString(v)
		b.WriteByte('\n')
	}
	return b.String()
}

// fzCloneStore deep-copies a MemStore through the public Store interface
// only (no reach into MemStore's private field), so it stays valid even if
// store.go's internals ever change shape.
func fzCloneStore(s *MemStore) *MemStore {
	out := NewMemStore()
	for _, k := range s.Keys() {
		v, _ := s.Get(k)
		out.Set(k, v)
	}
	return out
}

// fzRescanEscrowed is the GROUND-TRUTH count of credits currently PENDING in
// escrow for a creator: walk every issued seq and sum the ones still
// PENDING. O(seq count) — cheap for the small, short-lived worlds the
// ordering-immunity test builds; too expensive to call every step of a
// 50,000-step walk, which is why fzWorld also keeps an O(1) incremental
// model (escrowed) that this function periodically cross-checks.
func fzRescanEscrowed(s Store, creator string) *big.Int {
	total := big.NewInt(0)
	seqMax := getU64(s, kSeq(creator))
	for seq := uint64(0); seq < seqMax; seq++ {
		rec, ok := loadEscrow(s, creator, seq)
		if ok && rec.status == askPending {
			total = mAdd(total, rec.credits)
		}
	}
	return total
}

// fzRescanEscrowedCommission is fzRescanEscrowed's twin for the HBD
// commission leg (2026-07-20 defect fix): Ask no longer books the
// commission to the treasury immediately — it HOLDS it in the escrow
// record, and only Answer (books it) or Reclaim (returns it) resolve it —
// see ask.go's Ask/Answer/Reclaim doc. Same O(seq count) ground-truth walk,
// same PENDING-only filter, same "too expensive for every step of a
// 50,000-step walk" reasoning — fzWorld's heldCommission field is this
// quantity's O(1) incremental twin, periodically cross-checked against this.
func fzRescanEscrowedCommission(s Store, creator string) *big.Int {
	total := big.NewInt(0)
	seqMax := getU64(s, kSeq(creator))
	for seq := uint64(0); seq < seqMax; seq++ {
		rec, ok := loadEscrow(s, creator, seq)
		if ok && rec.status == askPending {
			total = mAdd(total, rec.commissionHbd)
		}
	}
	return total
}

func fzEscrowedSnapshot(s *MemStore) map[string]*big.Int {
	m := map[string]*big.Int{}
	for _, c := range fzCreators {
		m[c] = fzRescanEscrowed(s, c)
	}
	return m
}

// ---------------------------------------------------------------------------
// fzTrace — a replayable, printable log of one random walk. On failure,
// dump(t, tail) prints the seed and the last `tail` steps: re-seeding
// math/rand.NewSource(seed) and re-running the SAME generator deterministically
// reproduces this exact walk, since nothing here reads wall-clock time or
// depends on Go map iteration order for control flow.
// ---------------------------------------------------------------------------

type fzTrace struct {
	seed  int64
	lines []string
}

func (tr *fzTrace) add(format string, args ...interface{}) {
	tr.lines = append(tr.lines, fmt.Sprintf(format, args...))
}

func (tr *fzTrace) dump(t *testing.T, tail int) {
	t.Helper()
	n := len(tr.lines)
	start := 0
	if n > tail {
		start = n - tail
	}
	// NOTE: the bracketed number is this LINE's position in the log, not the
	// outer loop's iteration count — some iterations emit more than one line
	// (e.g. an auto-Register before a tiny op). The step number named in the
	// failing assertion itself (e.g. "step 396: ...") is the authoritative
	// loop iteration; replay by re-seeding rand.NewSource(seed) and re-running
	// the same generator, which is fully deterministic regardless of logging.
	t.Logf("=== fzTrace: seed=%d, %d total log lines, showing entries %d..%d ===", tr.seed, n, start, n-1)
	for i := start; i < n; i++ {
		t.Logf("[entry %d] %s", i, tr.lines[i])
	}
}

// ---------------------------------------------------------------------------
// fzWorld — one long randomized walk's mutable state: the Store, the
// monotonically non-decreasing block clock (block height only ever moves
// FORWARD on a real chain — twap.go leans on this explicitly: "write order
// IS block order"), the incremental escrow model, and the running HBD
// accounting ledger the solvency / no-free-money properties check.
// ---------------------------------------------------------------------------

type fzEscrowRef struct {
	creator       string
	seq           uint64
	asker         string
	deadline      uint64
	credits       *big.Int
	commissionHbd *big.Int // HBD held against this escrow — see fzWorld.heldCommission
}

type fzWorld struct {
	s     *MemStore
	block uint64

	escrowed map[string]*big.Int // creator -> Σ credits PENDING in escrow (incremental, O(1))

	// heldCommission — creator -> Σ HBD commission PENDING in escrow
	// (incremental, O(1)), the 2026-07-20 defect fix's new resting state
	// for HBD: Ask HOLDS the commission here instead of booking it to the
	// treasury immediately; Answer moves it to treasury, Reclaim returns
	// it to the asker (see ask.go). The global HBD identity check
	// (fzCheckSolvencyCore) needs this as a THIRD bucket alongside
	// reserve/treasury, or a market with any outstanding, unanswered ask
	// looks like it lost HBD that is actually just held, not gone.
	heldCommission map[string]*big.Int

	paidIn   map[string]*big.Int // actor -> Σ HBD it has paid IN (Register fee + Renew paid + Buy TotalDue + Ask commission)
	received map[string]*big.Int // actor -> Σ HBD it has received OUT (Sell net, fee claims, Refund/RefundHolder payouts, credited to the true payee)

	totalHBDIn  *big.Int
	totalHBDOut *big.Int

	// refunded[c] — has this market incarnation performed a wind-down refund
	// yet? While false the walk asserts reserve == area(supply) EXACTLY;
	// after the first refund only >= (the file-header invariant). Reset to
	// false by a successful re-Register (fresh incarnation, R back to 0).
	refunded map[string]bool

	pendingEscrows []fzEscrowRef
}

func fzNewWorld() *fzWorld {
	w := &fzWorld{
		s:              NewMemStore(),
		escrowed:       map[string]*big.Int{},
		heldCommission: map[string]*big.Int{},
		paidIn:         map[string]*big.Int{},
		received:       map[string]*big.Int{},
		totalHBDIn:     big.NewInt(0),
		totalHBDOut:    big.NewInt(0),
		refunded:       map[string]bool{},
	}
	for _, c := range fzCreators {
		w.escrowed[c] = big.NewInt(0)
		w.heldCommission[c] = big.NewInt(0)
	}
	for _, a := range fzAllActors {
		w.paidIn[a] = big.NewInt(0)
		w.received[a] = big.NewInt(0)
	}
	return w
}

func (w *fzWorld) pay(actor string, amt *big.Int) {
	if amt == nil {
		return
	}
	w.paidIn[actor] = mAdd(w.paidIn[actor], amt)
	w.totalHBDIn = mAdd(w.totalHBDIn, amt)
}

func (w *fzWorld) receive(actor string, amt *big.Int) {
	if amt == nil {
		return
	}
	w.received[actor] = mAdd(w.received[actor], amt)
	w.totalHBDOut = mAdd(w.totalHBDOut, amt)
}

// ---------------------------------------------------------------------------
// fz random-value generators. Every one is adversarial-biased: boundary
// values, zero, negative, huge, and "typical" are all in the mix, not just
// plausible happy-path numbers.
// ---------------------------------------------------------------------------

func fzAmount(rng *rand.Rand) *big.Int {
	switch rng.Intn(8) {
	case 0:
		return big.NewInt(0)
	case 1:
		return big.NewInt(1)
	case 2:
		return big.NewInt(-1)
	case 3:
		return nil
	case 4:
		return big.NewInt(int64(1 + rng.Intn(1000)))
	case 5:
		return big.NewInt(int64(1 + rng.Intn(1_000_000)))
	case 6:
		huge, _ := new(big.Int).SetString("1"+strings.Repeat("0", 20+rng.Intn(15)), 10)
		return huge
	default:
		return big.NewInt(int64(1 + rng.Intn(200)))
	}
}

// fzTransferAmount is biased toward the CURRENT balance so Refund/Transfer
// actions in the main walk often actually succeed (not just always hit
// ErrBalance), while still trying fully adversarial and over-balance amounts
// some of the time.
func fzTransferAmount(rng *rand.Rand, bal *big.Int) *big.Int {
	switch rng.Intn(4) {
	case 0:
		return fzAmount(rng)
	case 1:
		if bal.Sign() > 0 {
			return new(big.Int).Set(bal)
		}
		return big.NewInt(1)
	case 2:
		if bal.Sign() > 0 && bal.IsInt64() && bal.Int64() > 1 {
			return big.NewInt(1 + rng.Int63n(bal.Int64()))
		}
		return big.NewInt(1)
	default:
		return new(big.Int).Add(bal, big.NewInt(int64(1+rng.Intn(1000))))
	}
}

func fzRateLike(rng *rand.Rand) *big.Int {
	switch rng.Intn(8) {
	case 0:
		return big.NewInt(0)
	case 1:
		return big.NewInt(-1)
	case 2:
		return big.NewInt(1) // exactly PAR
	case 3:
		return big.NewInt(int64(1 + rng.Intn(1000)))
	case 4:
		return big.NewInt(int64(1 + rng.Intn(1_000_000)))
	case 5:
		huge, _ := new(big.Int).SetString("1"+strings.Repeat("0", 25+rng.Intn(15)), 10)
		return huge
	default:
		return big.NewInt(int64(1 + rng.Intn(50)))
	}
}

// fzRateLikePositive guarantees a strictly positive rate — used where the
// test needs Ask/AskRate to have a chance to succeed so it can check what
// happens on the success path (the guard/rejection paths are covered
// separately via fzRateLike in the main walk).
func fzRateLikePositive(rng *rand.Rand) *big.Int {
	r := fzRateLike(rng)
	if r.Sign() <= 0 {
		return big.NewInt(1)
	}
	return r
}

func fzFeeLike(rng *rand.Rand, required int64) *big.Int {
	switch rng.Intn(6) {
	case 0:
		return nil
	case 1:
		return big.NewInt(required - 1)
	case 2:
		return big.NewInt(required)
	case 3:
		return big.NewInt(required + 1)
	case 4:
		return new(big.Int).Mul(big.NewInt(required), big.NewInt(1+int64(rng.Intn(5))))
	default:
		return big.NewInt(required)
	}
}

func fzBoundaryInt64(rng *rand.Rand, lo, hi int64) int64 {
	switch rng.Intn(9) {
	case 0:
		return lo - 1
	case 1:
		return lo
	case 2:
		return lo + 1
	case 3:
		return hi - 1
	case 4:
		return hi
	case 5:
		return hi + 1
	case 6:
		return 0
	case 7:
		return hi + 1 + int64(rng.Intn(1_000_000))
	default:
		if hi <= lo {
			return lo
		}
		return lo + rng.Int63n(hi-lo+1)
	}
}

func fzBoundaryUint64(rng *rand.Rand, lo, hi uint64) uint64 {
	switch rng.Intn(9) {
	case 0:
		if lo > 0 {
			return lo - 1
		}
		return 0
	case 1:
		return lo
	case 2:
		return lo + 1
	case 3:
		return hi - 1
	case 4:
		return hi
	case 5:
		return hi + 1
	case 6:
		return 0
	case 7:
		return hi + 1 + uint64(rng.Intn(1_000_000))
	default:
		if hi <= lo {
			return lo
		}
		return lo + uint64(rng.Int63n(int64(hi-lo+1)))
	}
}

// ---------------------------------------------------------------------------
// fz action menu — one function per operation in the API.md surface, each
// mutating a shared fzWorld and logging to a shared fzTrace. Every action is
// safe to call in ANY state: failures are expected and are themselves part
// of the property being tested (a rejected call must never partially mutate
// state — the invariant checks below would catch that regardless of which
// action caused it).
// ---------------------------------------------------------------------------

// fzActRegister — registration is FREE (no fee argument exists any more),
// and it carries the OPTIONAL atomic creator first buy (launch.go). The
// launch buy is fuzzed here rather than in a separate action because it is
// not a separate operation: it is one state transition with the
// registration, so the invariant sweep must see it as one.
//
// The firstBuy draw deliberately includes nil, zero, NEGATIVE and huge
// values: a negative or over-cap firstBuy must be REFUSED with nothing
// mutated (no half-registered market — RULING G across a two-part
// transition), which the harness's post-action invariant sweep verifies for
// free.
func fzActRegister(t *testing.T, rng *rand.Rand, w *fzWorld, tr *fzTrace) {
	c := fzCreators[rng.Intn(len(fzCreators))]
	face := fzBoundaryInt64(rng, MinFace, MaxFace)
	cap := fzBoundaryInt64(rng, MinCap, MaxCap)

	var firstBuy *big.Int
	switch rng.Intn(4) {
	case 0:
		firstBuy = nil // the plain registration
	case 1:
		firstBuy = mZero() // explicit "no launch buy"
	case 2:
		firstBuy = big.NewInt(-1 - rng.Int63n(1000)) // must be refused
	default:
		firstBuy = fzAmount(rng) // 0/1/-1/nil/huge/ordinary
	}

	res, err := RegisterWithFirstBuy(w.s, c, c, w.block, face, cap, firstBuy)
	tr.add("RegisterWithFirstBuy(creator=%s block=%d face=%d cap=%d firstBuy=%v) -> err=%v", c, w.block, face, cap, firstBuy, err)
	if err == nil {
		// The creator pays the launch buy's cost+fee out of their own wallet,
		// exactly like any other buyer (zero for a plain registration).
		w.pay(c, res.TotalDue)
		// Fresh incarnation: R is provably area(S) — 0 with no launch buy,
		// area(n) with one (Buy's own induction step) — so the equality form
		// is assertable again.
		w.refunded[c] = false
	}
}

func fzActRenew(t *testing.T, rng *rand.Rand, w *fzWorld, tr *fzTrace) {
	c := fzCreators[rng.Intn(len(fzCreators))]
	payer := fzHolders[rng.Intn(len(fzHolders))]
	periods := uint64(fzBoundaryInt64(rng, 1, int64(MaxPrepaidPeriods)))
	paid := fzFeeLike(rng, SubscriptionFee*int64(periods))

	err := Renew(w.s, payer, c, w.block, periods, paid)
	tr.add("Renew(payer=%s creator=%s block=%d periods=%d paid=%v) -> err=%v", payer, c, w.block, periods, paid, err)
	if err == nil {
		w.pay(payer, paid)
	}
}

// fzActBuy — the ONLY issuance path (Buy on the curve; the PAR Prepay this
// action replaced is deleted with its mechanism). The amount fuzzed is the
// TOKEN COUNT n; the HBD drawn is the result's TotalDue (cost + fee), which
// is what the money model books.
func fzActBuy(t *testing.T, rng *rand.Rand, w *fzWorld, tr *fzTrace) {
	c := fzCreators[rng.Intn(len(fzCreators))]
	h := fzHolders[rng.Intn(len(fzHolders))]
	n := fzAmount(rng)

	res, err := Buy(w.s, h, c, w.block, n)
	if err == nil {
		tr.add("Buy(holder=%s creator=%s block=%d n=%v) -> due=%v", h, c, w.block, n, res.TotalDue)
		w.pay(h, res.TotalDue)
	} else {
		tr.add("Buy(holder=%s creator=%s block=%d n=%v) -> err=%v", h, c, w.block, n, err)
	}
}

// fzActSell — the curve exit during ACTIVE/OVERDUE. The seller receives Net;
// the tax lands in the treasury and the fee halves in the pull pots (all
// read live from state by the global identity).
func fzActSell(t *testing.T, rng *rand.Rand, w *fzWorld, tr *fzTrace) {
	c := fzCreators[rng.Intn(len(fzCreators))]
	h := fzHolders[rng.Intn(len(fzHolders))]
	bal := getMoney(w.s, kBal(c, h))
	amt := fzTransferAmount(rng, bal)

	res, err := Sell(w.s, h, c, w.block, amt)
	if err == nil {
		tr.add("Sell(holder=%s creator=%s block=%d dS=%v) -> p=%v tax=%v net=%v", h, c, w.block, amt, res.Gross, res.Tax, res.Net)
		w.receive(h, res.Net)
	} else {
		tr.add("Sell(holder=%s creator=%s block=%d dS=%v) -> err=%v", h, c, w.block, amt, err)
	}
}

// fzActClaimFees — the pull-claimable trade-fee outflow (F8). Never gated;
// a zero claim is a harmless no-op by ClaimTradeFees' own contract.
func fzActClaimFees(t *testing.T, rng *rand.Rand, w *fzWorld, tr *fzTrace) {
	a := fzAllActors[rng.Intn(len(fzAllActors))]
	owed, err := ClaimTradeFees(w.s, a)
	tr.add("ClaimTradeFees(%s) -> %v err=%v", a, owed, err)
	if err == nil && owed.Sign() > 0 {
		w.receive(a, owed)
	}
}

func fzActTransferCredits(t *testing.T, rng *rand.Rand, w *fzWorld, tr *fzTrace) {
	c := fzCreators[rng.Intn(len(fzCreators))]
	from := fzHolders[rng.Intn(len(fzHolders))]
	to := fzHolders[rng.Intn(len(fzHolders))]
	for to == from {
		to = fzHolders[rng.Intn(len(fzHolders))]
	}
	bal := getMoney(w.s, kBal(c, from))
	amt := fzTransferAmount(rng, bal)

	// F12 fix (2026-08-19): TransferCredits now takes an explicit `caller`
	// and refuses caller != from (transfer.go). This fuzz world has no
	// separate "signer" identity distinct from `from`/`to`, so this action
	// always calls as the consenting owner (caller == from) — it exercises
	// the money-conservation/invariant surface of a legitimate transfer, not
	// authorization; the authorization gap itself is the dedicated,
	// now-closed finding in TestFuzzNoFreeMoney.
	err := TransferCredits(w.s, from, c, from, to, w.block, amt)
	tr.add("TransferCredits(creator=%s from=%s to=%s block=%d amt=%v) -> err=%v", c, from, to, w.block, amt, err)
}

func fzActAsk(t *testing.T, rng *rand.Rand, w *fzWorld, tr *fzTrace) {
	c := fzCreators[rng.Intn(len(fzCreators))]
	asker := fzHolders[rng.Intn(len(fzHolders))]

	// maxCredits (2026-07-20 fix: Ask no longer takes `rate` as a
	// parameter — it derives its own settlement rate internally via
	// SettlementRate; see ask.go's doc). Reused generator: fzRateLike
	// already produces the exact "occasionally zero/negative (exercises
	// the maxCredits-must-be->0 guard), occasionally tiny-but-positive
	// (exercises the slippage-exceeded guard), occasionally huge (lets Ask
	// succeed unconstrained)" shape a rate used to need here.
	maxCredits := fzRateLike(rng)

	face := getMoney(w.s, kFace(c))
	owed := commissionOwedFor(face)
	commission := fzFeeLike(rng, fzBigToInt64Safe(owed))
	deadline := fzBoundaryUint64(rng, MinAskDeadline, MaxAskDeadline)
	contentHash := fmt.Sprintf("cid-%d-%d", w.block, rng.Int63())

	res, err := askAt0(w.s, asker, c, w.block, maxCredits, commission, contentHash, deadline)
	tr.add("Ask(asker=%s creator=%s block=%d maxCredits=%v commission=%v deadline=%d face=%s) -> res=%+v err=%v",
		asker, c, w.block, maxCredits, commission, deadline, face, res, err)

	if err != nil {
		return
	}

	w.pay(asker, commission)
	w.escrowed[c] = mAdd(w.escrowed[c], res.CreditsSpent)
	// heldCommission (2026-07-20 fix): the commission is HELD against this
	// escrow, not booked to treasury yet — see fzWorld.heldCommission's doc
	// and fzCheckSolvencyCore's global HBD identity, which needs this as a
	// third resting-state bucket.
	w.heldCommission[c] = mAdd(w.heldCommission[c], res.CommissionHbd)
	w.pendingEscrows = append(w.pendingEscrows, fzEscrowRef{
		creator: c, seq: res.Seq, asker: asker, deadline: w.block + deadline, credits: res.CreditsSpent, commissionHbd: res.CommissionHbd,
	})

	// Property #4, checked live on EVERY successful ask across every test in
	// this file, not only in the dedicated rounding test: creditsForAsk must
	// be the exact independent ceiling, never fewer (which would shortchange
	// the reserve). Checked against res.RateUsed — the rate Ask ACTUALLY
	// derived internally (SettlementRate: TWAP-or-PAR) — never against a
	// fuzzer-picked value, since the fuzzer no longer controls the rate at
	// all.
	if res.RateUsed.Sign() > 0 && face.Sign() > 0 {
		want := fzCeilDiv(face, res.RateUsed)
		if res.CreditsSpent.Cmp(want) != 0 {
			tr.dump(t, 200)
			t.Fatalf("ROUNDING VIOLATION: Ask(face=%s rate=%s) CreditsSpent=%s, independent ceil=%s", face, res.RateUsed, res.CreditsSpent, want)
		}
	}

	// The maxCredits guard itself: a successful ask must never have spent
	// more than the asker's own signed cap.
	if mGt(res.CreditsSpent, maxCredits) {
		tr.dump(t, 200)
		t.Fatalf("SLIPPAGE GUARD VIOLATION: Ask spent %s credits, exceeding maxCredits=%s", res.CreditsSpent, maxCredits)
	}
}

func fzActAnswer(t *testing.T, rng *rand.Rand, w *fzWorld, tr *fzTrace) {
	if len(w.pendingEscrows) == 0 {
		tr.add("Answer: skip (no pending escrows)")
		return
	}
	idx := rng.Intn(len(w.pendingEscrows))
	ref := w.pendingEscrows[idx]

	res, err := Answer(w.s, ref.creator, ref.creator, w.block, ref.seq, fmt.Sprintf("ans-%d", rng.Int63()))
	tr.add("Answer(creator=%s seq=%d block=%d deadline=%d) -> res=%+v err=%v", ref.creator, ref.seq, w.block, ref.deadline, res, err)

	if err == nil {
		w.escrowed[ref.creator] = new(big.Int).Sub(w.escrowed[ref.creator], ref.credits)
		// The commission moves from "held in escrow" to the treasury
		// (core.Answer's own addMoney(kTreasury(), ...)) — treasury is read
		// live from state by fzCheckSolvencyCore, so it self-updates; this
		// just retires the now-resolved escrow from the heldCommission
		// bucket so it isn't double-counted.
		w.heldCommission[ref.creator] = new(big.Int).Sub(w.heldCommission[ref.creator], ref.commissionHbd)
		w.pendingEscrows = append(w.pendingEscrows[:idx], w.pendingEscrows[idx+1:]...)
	}
}

func fzActReclaim(t *testing.T, rng *rand.Rand, w *fzWorld, tr *fzTrace) {
	if len(w.pendingEscrows) == 0 {
		tr.add("Reclaim: skip (no pending escrows)")
		return
	}
	idx := rng.Intn(len(w.pendingEscrows))
	ref := w.pendingEscrows[idx]

	res, err := Reclaim(w.s, ref.asker, ref.creator, w.block, ref.seq)
	tr.add("Reclaim(asker=%s creator=%s seq=%d block=%d deadline=%d) -> res=%+v err=%v",
		ref.asker, ref.creator, ref.seq, w.block, ref.deadline, res, err)

	if err == nil {
		w.escrowed[ref.creator] = new(big.Int).Sub(w.escrowed[ref.creator], ref.credits)
		w.heldCommission[ref.creator] = new(big.Int).Sub(w.heldCommission[ref.creator], ref.commissionHbd)
		// core.Reclaim now ALSO returns the held commission (2026-07-20
		// defect fix — SPEC §1.7.2 rule 4: 100% back on an unanswered ask).
		// core itself never moves HBD, but a real wasm `reclaim` entrypoint
		// DOES sdk.HiveTransfer this back to the asker (see
		// contract/main.go's Reclaim entrypoint) — a genuine outflow this
		// model must record, exactly like a Refund payout, or the global
		// HBD identity would see it vanish from heldCommission with nowhere
		// else to land.
		w.receive(ref.asker, res.CommissionHbd)
		w.pendingEscrows = append(w.pendingEscrows[:idx], w.pendingEscrows[idx+1:]...)
	}
}

func fzActRefund(t *testing.T, rng *rand.Rand, w *fzWorld, tr *fzTrace) {
	c := fzCreators[rng.Intn(len(fzCreators))]
	h := fzHolders[rng.Intn(len(fzHolders))]
	bal := getMoney(w.s, kBal(c, h))
	amt := fzTransferAmount(rng, bal)

	payout, err := Refund(w.s, h, c, w.block, amt)
	tr.add("Refund(holder=%s creator=%s block=%d amt=%v) -> payout=%v err=%v", h, c, w.block, amt, payout, err)
	if err == nil {
		w.receive(h, payout)
		w.refunded[c] = true // pro-rata floor dust may now sit above area(S)
	}
}

func fzActRefundHolder(t *testing.T, rng *rand.Rand, w *fzWorld, tr *fzTrace) {
	c := fzCreators[rng.Intn(len(fzCreators))]
	h := fzHolders[rng.Intn(len(fzHolders))]
	pusher := fzHolders[rng.Intn(len(fzHolders))] // deliberately independent of h — anyone may push

	// BOTH buckets: a wholly-matured holder has no maturing key, so reading
	// kBal alone reports 0 and the "a real burn happened" flag never gets set —
	// after which the R == area(S) equality check fires on a market that has
	// legitimately begun its wind-down.
	balBefore := totalBalance(w.s, c, h)
	payout, err := RefundHolder(w.s, pusher, c, h, w.block)
	tr.add("RefundHolder(pusher=%s creator=%s holder=%s block=%d) -> payout=%v err=%v", pusher, c, h, w.block, payout, err)
	if err == nil {
		w.receive(h, payout) // pays the HOLDER, never the pusher — see RefundHolder's own doc
		if balBefore.Sign() > 0 {
			w.refunded[c] = true // a real burn happened (zero-balance calls are documented no-ops)
		}
	}
}

func fzActSetFace(t *testing.T, rng *rand.Rand, w *fzWorld, tr *fzTrace) {
	c := fzCreators[rng.Intn(len(fzCreators))]
	newFace := fzBoundaryInt64(rng, MinFace, MaxFace)
	err := SetFace(w.s, c, c, w.block, newFace)
	tr.add("SetFace(creator=%s block=%d newFace=%d) -> err=%v", c, w.block, newFace, err)
}

func fzActSetCap(t *testing.T, rng *rand.Rand, w *fzWorld, tr *fzTrace) {
	c := fzCreators[rng.Intn(len(fzCreators))]
	newCap := fzBoundaryInt64(rng, MinCap, MaxCap)
	err := SetCap(w.s, c, c, w.block, newCap)
	tr.add("SetCap(creator=%s block=%d newCap=%d) -> err=%v", c, w.block, newCap, err)
}

func fzActCloseIfDrained(t *testing.T, rng *rand.Rand, w *fzWorld, tr *fzTrace) {
	c := fzCreators[rng.Intn(len(fzCreators))]
	closed := CloseIfDrained(w.s, c, w.block)
	tr.add("CloseIfDrained(creator=%s block=%d) -> closed=%v", c, w.block, closed)
}

func fzActRecordObs(t *testing.T, rng *rand.Rand, w *fzWorld, tr *fzTrace) {
	c := fzCreators[rng.Intn(len(fzCreators))]
	rate := fzRateLike(rng)
	RecordObs(w.s, c, w.block, rate)
	tr.add("RecordObs(creator=%s block=%d rate=%v)", c, w.block, rate)
}

func fzActAdvanceBlock(t *testing.T, rng *rand.Rand, w *fzWorld, tr *fzTrace) {
	var delta uint64
	switch rng.Intn(10) {
	case 0:
		delta = 0 // same-block batch — exercises I6 / TWAP dedup
	case 1:
		delta = 1
	case 2, 3, 4:
		delta = uint64(1 + rng.Intn(2000))
	case 5, 6:
		delta = SubscriptionPeriod
	case 7:
		delta = GraceBlocks
	case 8:
		delta = ReclaimGrace
	default:
		delta = uint64(1 + rng.Intn(500_000))
	}
	w.block += delta
	tr.add("AdvanceBlock(+%d) -> block=%d", delta, w.block)
}

func fzApplyRandomAction(t *testing.T, rng *rand.Rand, w *fzWorld, tr *fzTrace) {
	switch rng.Intn(16) {
	case 0:
		fzActRegister(t, rng, w, tr)
	case 1:
		fzActRenew(t, rng, w, tr)
	case 2:
		fzActBuy(t, rng, w, tr)
	case 3:
		fzActAsk(t, rng, w, tr)
	case 4:
		fzActAnswer(t, rng, w, tr)
	case 5:
		fzActReclaim(t, rng, w, tr)
	case 6:
		fzActTransferCredits(t, rng, w, tr)
	case 7:
		fzActRefund(t, rng, w, tr)
	case 8:
		fzActRefundHolder(t, rng, w, tr)
	case 9:
		fzActSetFace(t, rng, w, tr)
	case 10:
		fzActSetCap(t, rng, w, tr)
	case 11:
		fzActCloseIfDrained(t, rng, w, tr)
	case 12:
		fzActRecordObs(t, rng, w, tr)
	case 13:
		fzActSell(t, rng, w, tr)
	case 14:
		fzActClaimFees(t, rng, w, tr)
	default:
		fzActAdvanceBlock(t, rng, w, tr)
	}
}

// fzApplyRandomActionExceptTransfer is the same action menu minus
// TransferCredits — used only by TestFuzzNoFreeMoney/RandomWalk (see the
// call site's comment for why).
func fzApplyRandomActionExceptTransfer(t *testing.T, rng *rand.Rand, w *fzWorld, tr *fzTrace) {
	switch rng.Intn(15) {
	case 0:
		fzActRegister(t, rng, w, tr)
	case 1:
		fzActRenew(t, rng, w, tr)
	case 2:
		fzActBuy(t, rng, w, tr)
	case 3:
		fzActAsk(t, rng, w, tr)
	case 4:
		fzActAnswer(t, rng, w, tr)
	case 5:
		fzActReclaim(t, rng, w, tr)
	case 6:
		fzActRefund(t, rng, w, tr)
	case 7:
		fzActRefundHolder(t, rng, w, tr)
	case 8:
		fzActSetFace(t, rng, w, tr)
	case 9:
		fzActSetCap(t, rng, w, tr)
	case 10:
		fzActCloseIfDrained(t, rng, w, tr)
	case 11:
		fzActRecordObs(t, rng, w, tr)
	case 12:
		fzActSell(t, rng, w, tr)
	case 13:
		fzActClaimFees(t, rng, w, tr)
	default:
		fzActAdvanceBlock(t, rng, w, tr)
	}
}

// ---------------------------------------------------------------------------
// fz invariant checks — the heart of properties #1 and #2.
// ---------------------------------------------------------------------------

// fzCheckInvariantsOnStore checks the CURVE INVARIANT's store-only half
// (reserve >= area(supply) — see the file header; the walk-tracked equality
// half lives in fzCheckSolvencyCore, which knows whether the incarnation
// has refunded yet) and I3 (supply == Σbal + escrowed) against a bare
// store, given an escrowed map the caller supplies (either fzWorld's O(1)
// incremental model, or a fresh fzRescanEscrowed snapshot for a standalone
// clone). No external ledger required, so this is valid for ANY Store,
// including a permutation-test clone that was never part of a tracked walk.
func fzCheckInvariantsOnStore(t *testing.T, s *MemStore, tr *fzTrace, label string, escrowed map[string]*big.Int) {
	t.Helper()
	for _, c := range fzCreators {
		reserve := getMoney(s, kReserve(c))
		supply := getMoney(s, kSupply(c))
		if reserve.Sign() < 0 || supply.Sign() < 0 {
			tr.dump(t, 200)
			t.Fatalf("%s: NEGATIVE money for %s: reserve=%s supply=%s", label, c, reserve, supply)
		}
		if reserve.Cmp(Area(supply)) < 0 {
			tr.dump(t, 200)
			t.Fatalf("%s: RESERVE UNDER THE CURVE for %s: reserve=%s < area(%s)=%s — the backing promise is broken", label, c, reserve, supply, Area(supply))
		}
		sumBal := big.NewInt(0)
		for _, h := range fzAllActors {
			// BOTH buckets — a graduated holder holds no maturing key.
			sumBal = mAdd(sumBal, totalBalance(s, c, h))
		}
		esc := escrowed[c]
		if esc == nil {
			esc = mZero()
		}
		want := mAdd(sumBal, esc)
		if supply.Cmp(want) != 0 {
			tr.dump(t, 200)
			t.Fatalf("%s: I3 VIOLATED for %s: supply=%s, Σbal=%s + escrowed=%s = %s", label, c, supply, sumBal, esc, want)
		}
	}
}

// fzCheckSolvencyCore is EXACTLY property #1's literal scope (API.md I1/I3,
// plus the global HBD identity): PEG+I3, both forms of I1, and the global
// HBD accounting identity. It deliberately does NOT check the per-actor
// no-free-money property (#2) — that is a distinct property with its own
// test, and bundling it here would make property #1 fail for reasons
// entirely outside its stated scope (e.g. the TransferCredits authorization
// gap documented in TestFuzzNoFreeMoney moves CREDITS between holders, never
// HBD, so it cannot violate solvency/I1/I3/the global identity at all — but
// it WOULD trip a bundled no-free-money check, for a reason unrelated to
// what property #1 is meant to verify).
func fzCheckSolvencyCore(t *testing.T, w *fzWorld, tr *fzTrace, step int) {
	t.Helper()
	label := fmt.Sprintf("step %d", step)
	fzCheckInvariantsOnStore(t, w.s, tr, label, w.escrowed)

	treasury := getMoney(w.s, kTreasury())
	reserveSum := big.NewInt(0)
	heldCommissionSum := big.NewInt(0)

	for _, c := range fzCreators {
		reserve := getMoney(w.s, kReserve(c))
		supply := getMoney(w.s, kSupply(c))
		reserveSum = mAdd(reserveSum, reserve)
		heldCommissionSum = mAdd(heldCommissionSum, w.heldCommission[c])

		// THE CURVE INVARIANT's equality half (file header): until this
		// incarnation's first wind-down refund, R == area(S) EXACTLY — any
		// upward drift is an ownerless pot forming (the forbidden class),
		// any downward drift is a backing hole.
		if !w.refunded[c] && reserve.Cmp(Area(supply)) != 0 {
			tr.dump(t, 200)
			t.Fatalf("%s: EQUALITY BROKEN for %s (no refund yet this incarnation): reserve=%s != area(%s)=%s",
				label, c, reserve, supply, Area(supply))
		}

		// I1, literal wording: "reserve >= sum of all refunds payable at the
		// current refund price". RefundPrice quotes HBD per a SINGLE credit,
		// floored — a coarse bound (often 0 once reserve<supply by even 1
		// unit) but it is the literal quantity API.md names, so it is checked
		// explicitly and separately from the rigorous form below.
		price := RefundPrice(w.s, c)
		coarse := new(big.Int).Mul(price, supply)
		if coarse.Cmp(reserve) > 0 {
			tr.dump(t, 200)
			t.Fatalf("%s: I1 (literal RefundPrice bound) VIOLATED for %s: price=%s*supply=%s=%s > reserve=%s", label, c, price, supply, coarse, reserve)
		}

		// I1, rigorous form: simulate a real full unwind of every CURRENTLY
		// HELD balance (escrowed credits aren't redeemable by anyone yet, so
		// they're excluded) using the package's own refundPayout formula,
		// WITHOUT mutating real state. Must never exceed reserve; and when
		// NO credits sit in escrow (Σbal == supply), the unwind must drain
		// the reserve to EXACTLY zero — C-24 terminal exactness: the last
		// claim pays floor(R·S/S) == R, so over any complete wind-down
		// Σ payouts == R with zero stranded residual.
		if supply.Sign() > 0 {
			rc, sc := new(big.Int).Set(reserve), new(big.Int).Set(supply)
			total := big.NewInt(0)
			sumBal := big.NewInt(0)
			for _, h := range fzAllActors {
				// BOTH buckets — a wind-down pays a holder's whole position, so
				// simulating it from the maturing half alone strands the matured
				// half's backing and reports a residual that does not exist.
				bal := totalBalance(w.s, c, h)
				if bal.Sign() <= 0 {
					continue
				}
				sumBal = mAdd(sumBal, bal)
				payout := refundPayout(rc, bal, sc)
				total = mAdd(total, payout)
				rc = new(big.Int).Sub(rc, payout)
				sc = new(big.Int).Sub(sc, bal)
			}
			if total.Cmp(reserve) > 0 {
				tr.dump(t, 200)
				t.Fatalf("%s: I1 (simulated full unwind) VIOLATED for %s: Σpayout=%s > reserve=%s", label, c, total, reserve)
			}
			esc := w.escrowed[c]
			if (esc == nil || esc.Sign() == 0) && total.Cmp(reserve) != 0 {
				tr.dump(t, 200)
				t.Fatalf("%s: C-24 VIOLATED for %s: complete simulated unwind paid Σ=%s, want the WHOLE reserve %s (zero stranded residual)", label, c, total, reserve)
			}
		}
	}

	// Global HBD accounting identity — exact. The reserve legs move by exact
	// area steps and pro-rata payouts, the fee/tax legs by their exact split
	// amounts, so the identity has zero tolerance:
	//   total HBD in == total HBD out + Σ reserve + treasury
	//                   + Σ heldCommission + Σ kFeeBal
	// heldCommission: a pending ask's commission has been drawn from the
	// asker (counted in totalHBDIn via w.pay at Ask time) but is neither in
	// a market's reserve nor booked to the treasury yet. kFeeBal: the
	// creators' pull-claimable trade-fee halves (F8) — drawn from buyers /
	// carved from sellers, resting until ClaimTradeFees pays them out. The
	// treasury (read live) self-accounts the platform fee halves, the
	// RULING-J exit taxes, registration/renewal fees and delivered
	// commissions.
	feeBalSum := big.NewInt(0)
	for _, a := range fzAllActors {
		feeBalSum = mAdd(feeBalSum, getMoney(w.s, kFeeBal(a)))
	}
	rhs := mAdd(mAdd(mAdd(mAdd(w.totalHBDOut, reserveSum), treasury), heldCommissionSum), feeBalSum)
	if w.totalHBDIn.Cmp(rhs) != 0 {
		tr.dump(t, 200)
		t.Fatalf("%s: GLOBAL HBD IDENTITY VIOLATED: in=%s, out=%s + reserve=%s + treasury=%s + heldCommission=%s + feeBals=%s = %s",
			label, w.totalHBDIn, w.totalHBDOut, reserveSum, treasury, heldCommissionSum, feeBalSum, rhs)
	}
}

// fzCheckNoFreeMoney is property #2's own check, kept separate from
// fzCheckSolvencyCore (see that function's doc comment for why).
//
// RE-SCOPED BY THE CURVE PORT, honestly: the old PAR-era form asserted the
// PER-ACTOR bound (nobody receives more than they paid). Under the curve
// that is FALSE BY DESIGN, twice over — an early buyer who sells after
// later buyers raised the supply legitimately profits (the disclosed
// curve-leg transfer from late buyers to early sellers, RULING J residual
// truth #1; proven with exact integers in curve_fuzz_test.go's by-design
// test), and a creator who DELIVERS earns credits they can legitimately
// monetize. What remains invariant — and is asserted here — is the SYSTEM
// bound: across all actors together, Σ received <= Σ paid in. The contract
// can only ever redistribute deposited HBD (minus what rests in the
// reserve/treasury/fee pots); it can never emit a unit it was not given.
// The per-actor property survives in its sound forms elsewhere: the
// solo-actor walk (curve_fuzz_test.go: one actor alone never profits) and
// the governing theorem (a fresh buyer never profits at wind-down —
// sell_test.go end-to-end, curve_test.go on the primitive).
func fzCheckNoFreeMoney(t *testing.T, w *fzWorld, tr *fzTrace, step int) {
	t.Helper()
	label := fmt.Sprintf("step %d", step)
	recvSum, paidSum := big.NewInt(0), big.NewInt(0)
	for _, actor := range fzAllActors {
		recvSum = mAdd(recvSum, w.received[actor])
		paidSum = mAdd(paidSum, w.paidIn[actor])
	}
	if recvSum.Cmp(paidSum) > 0 {
		tr.dump(t, 200)
		t.Fatalf("%s: NO-FREE-MONEY VIOLATED (system-wide): Σ received %s > Σ paid in %s — the contract emitted HBD it was never given", label, recvSum, paidSum)
	}
}

// fzCheckInvariants is the FULL gate — solvency core + no-free-money —
// used by TestFuzzNoFreeMoney, which is the one test whose stated scope
// covers both.
func fzCheckInvariants(t *testing.T, w *fzWorld, tr *fzTrace, step int) {
	t.Helper()
	fzCheckSolvencyCore(t, w, tr, step)
	fzCheckNoFreeMoney(t, w, tr, step)
}

// ===========================================================================
// Property #1 — SOLVENCY UNDER ANY SEQUENCE
// ===========================================================================

func TestFuzzSolvencyUnderAnySequence(t *testing.T) {
	const seed = int64(20260720001)
	const steps = 50000
	rng := rand.New(rand.NewSource(seed))
	w := fzNewWorld()
	w.block = 1
	tr := &fzTrace{seed: seed}

	for i := 0; i < steps; i++ {
		fzApplyRandomAction(t, rng, w, tr)
		// Property #1's literal scope only (I3/I1/global identity) — see
		// fzCheckSolvencyCore's doc comment for why no-free-money is excluded.
		fzCheckSolvencyCore(t, w, tr, i)

		if i > 0 && i%500 == 0 {
			for _, c := range fzCreators {
				got := fzRescanEscrowed(w.s, c)
				if got.Cmp(w.escrowed[c]) != 0 {
					tr.dump(t, 200)
					t.Fatalf("step %d: escrow-model drift for %s: incremental=%s, ground-truth rescan=%s", i, c, w.escrowed[c], got)
				}
				gotCommission := fzRescanEscrowedCommission(w.s, c)
				if gotCommission.Cmp(w.heldCommission[c]) != 0 {
					tr.dump(t, 200)
					t.Fatalf("step %d: heldCommission-model drift for %s: incremental=%s, ground-truth rescan=%s", i, c, w.heldCommission[c], gotCommission)
				}
			}
		}
	}
	t.Logf("TestFuzzSolvencyUnderAnySequence: %d steps passed (seed=%d), %d creators x %d holders, every invariant held after EVERY step",
		steps, seed, len(fzCreators), len(fzHolders))
}

// ===========================================================================
// Property #2 — NO FREE MONEY
// ===========================================================================

func TestFuzzNoFreeMoney(t *testing.T) {
	t.Run("RandomWalk", func(t *testing.T) {
		const seed = int64(20260720002)
		const steps = 30000
		rng := rand.New(rand.NewSource(seed))
		w := fzNewWorld()
		w.block = 1
		tr := &fzTrace{seed: seed}

		for i := 0; i < steps; i++ {
			// TransferCredits is EXCLUDED from this walk's action mix.
			// HISTORICAL REASON (pre-F12, before 2026-08-19): it had no
			// caller/authorization check at all, so including it here would
			// have made this walk re-discover that same already-proven
			// finding over and over instead of hunting for anything new.
			// F12 closed that gap (transfer.go now enforces caller == from),
			// and fzActTransferCredits always calls with a consenting caller
			// (see its own doc), so the exclusion is no longer load-bearing
			// for soundness — kept anyway to leave this walk's fixed-seed
			// trajectory (and everything it has already proven) undisturbed.
			// This walk's job is to catch OTHER, not-yet-known no-free-money
			// violations across the rest of the surface.
			fzApplyRandomActionExceptTransfer(t, rng, w, tr)
			// Independently seeded from TestFuzzSolvencyUnderAnySequence, so
			// this is a genuine second, decorrelated witness for every
			// solvency invariant too, not just the no-free-money slice of it.
			fzCheckInvariants(t, w, tr, i)
		}
		t.Logf("TestFuzzNoFreeMoney/RandomWalk: %d steps passed (seed=%d)", steps, seed)
	})

	// -----------------------------------------------------------------
	// F12 DEFECT FIX (2026-08-19) — was "Minimal, deterministic, documented
	// finding" (the redemption path is now Sell on the live market; the
	// PAR-exact payout expectation died with the peg).
	//
	// TransferCredits(s Store, caller, creator, from, to string, block
	// uint64, amount *big.Int) error (transfer.go) USED TO BE the one
	// money-moving function in this entire package with NO caller/
	// authorization parameter — every sibling function binds an explicit
	// `caller` to the account whose funds move:
	//   Refund(s, caller, creator, block, credits)      burns CALLER's own balance
	//   RefundHolder(s, caller, creator, holder, block)  caller is checked
	//     non-empty but is structurally incapable of being paid; only
	//     `holder` ever is
	//   Buy(s, caller, creator, block, n)                caller pays, caller mints
	//   Sell(s, caller, creator, block, deltaS)          caller burns OWN tokens
	//   Ask(s, caller, creator, ...)                     caller spends OWN credits
	// TransferCredits alone took `from` — an unauthenticated account name —
	// with nothing proving it was the transaction signer. The wasm wrapper
	// was therefore the ONLY authorization layer this function had; in-core,
	// the gap was real, and this test proved the theft end-to-end (an
	// attacker who never touched the market moved the victim's entire
	// balance to itself and liquidated it on the live curve for real HBD,
	// while every OTHER test in this repository still passed — nothing
	// caught it but this one, deliberately-adversarial test).
	//
	// THE FIX: TransferCredits now takes `caller` explicitly and refuses
	// caller != from internally (core/transfer.go). This subtest is KEPT,
	// in place, as the regression proof that the exact scenario above is now
	// refused rather than deleted once it stopped being a live finding — see
	// also the dedicated TestTransferCredits_RejectsCallerMismatch in
	// transfer_test.go, which is the canonical home for this guarantee.
	// -----------------------------------------------------------------
	t.Run("TransferCreditsRejectsCallerMismatch_F12_FIXED", func(t *testing.T) {
		s := NewMemStore()
		creator := "fzvictimmkt"
		victim := "fzvictim01"
		attacker := "fzattacker1"
		const block = uint64(1000)

		if err := Register(s, creator, creator, block, MinFace, MaxCap); err != nil {
			t.Fatalf("setup Register: %v", err)
		}
		stolen := big.NewInt(1000)
		if _, err := Buy(s, victim, creator, block, stolen); err != nil {
			t.Fatalf("setup Buy: %v", err)
		}
		if got := getMoney(s, kBal(creator, victim)); got.Cmp(stolen) != 0 {
			t.Fatalf("setup: victim balance = %s, want %s", got, stolen)
		}

		// The attacker has never interacted with this market and paid
		// nothing. It calls TransferCredits as itself (caller=attacker),
		// naming the VICTIM as `from`. This must now be refused.
		err := TransferCredits(s, attacker, creator, victim, attacker, block, stolen)
		if err == nil {
			t.Fatal("expected the unauthorized transfer to be REFUSED (F12 fix); it succeeded instead — the gap is back open")
		}
		if sym := errSymbol(err); sym != ErrAuth {
			t.Fatalf("want ErrAuth, got %v", err)
		}

		if got := getMoney(s, kBal(creator, victim)); got.Cmp(stolen) != 0 {
			t.Fatalf("victim balance after the REFUSED transfer = %s, want unchanged %s", got, stolen)
		}
		if got := getMoney(s, kBal(creator, attacker)); !mIsZero(got) {
			t.Fatalf("attacker balance = %s, want 0 (the transfer must not have moved anything)", got)
		}

		// The victim's own, self-authorized transfer of the SAME tokens
		// still works — the fix blocks impersonation, not legitimate use.
		if err := TransferCredits(s, victim, creator, victim, attacker, block, stolen); err != nil {
			t.Fatalf("victim's own consenting transfer unexpectedly rejected: %v", err)
		}
		if got := getMoney(s, kBal(creator, attacker)); got.Cmp(stolen) != 0 {
			t.Fatalf("attacker balance after victim's OWN transfer = %s, want %s", got, stolen)
		}
	})
}

// ===========================================================================
// Property #3 — ORDERING IMMUNITY
// ===========================================================================

// fzOpCandidate.apply returns BOTH an error and an "effect" string. The
// effect matters because several functions in this package can return
// err==nil for two semantically different outcomes — most notably
// RefundHolder, whose own doc explicitly documents a zero-balance call as "a
// harmless no-op: (0, nil)". Grouping permutations by success/fail ALONE
// would conflate "RefundHolder no-op'd because the target was empty at that
// point in the sequence" with "RefundHolder paid out 195" — both succeed,
// but they are NOT the same outcome, and requiring identical final state
// across the two would be a false positive, not a real I6-style violation.
// The effect string (e.g. "payout=0" vs "payout=195") makes the outcome key
// precise enough that only GENUINELY identical outcomes are compared.
type fzOpCandidate struct {
	id    string
	apply func(s *MemStore, block uint64) (effect string, err error)
}

func fzPermutations(n int) [][]int {
	if n == 0 {
		return [][]int{{}}
	}
	var out [][]int
	base := make([]int, n)
	for i := range base {
		base[i] = i
	}
	var perm func(cur, remaining []int)
	perm = func(cur, remaining []int) {
		if len(remaining) == 0 {
			cp := make([]int, len(cur))
			copy(cp, cur)
			out = append(out, cp)
			return
		}
		for i, v := range remaining {
			next := make([]int, 0, len(remaining)-1)
			next = append(next, remaining[:i]...)
			next = append(next, remaining[i+1:]...)
			perm(append(append([]int{}, cur...), v), next)
		}
	}
	perm(nil, base)
	return out
}

// fzBuildOrderingCandidates builds a diverse pool of candidate operations
// against the world `w` as it stands right now, all targeting the SAME
// block. Some are on disjoint creators/holders (trivially commuting), some
// deliberately share a creator (SetFace+SetCap: disjoint fields; two Buys
// on the same curve: NOT additive in price but exactly path-independent in
// total — curve.go L3's telescope, which is precisely what makes them
// order-immune; two RefundHolder pushes for different holders on the SAME
// creator: the genuinely non-trivial case, since each call re-reads the
// PREVAILING reserve/supply ratio), and every currently-pending escrow
// contributes both an Answer and a Reclaim candidate — the direct I6 pair.
func fzBuildOrderingCandidates(rng *rand.Rand, w *fzWorld) []fzOpCandidate {
	var cands []fzOpCandidate
	add := func(id string, apply func(s *MemStore, block uint64) (string, error)) {
		cands = append(cands, fzOpCandidate{id: id, apply: apply})
	}

	for i := 0; i < 3; i++ {
		c := fzCreators[rng.Intn(len(fzCreators))]
		h := fzHolders[rng.Intn(len(fzHolders))]
		n := big.NewInt(int64(1 + rng.Intn(200)))
		id := fmt.Sprintf("buy:%d:%s:%s:%s", i, c, h, n)
		add(id, func(s *MemStore, block uint64) (string, error) {
			res, err := Buy(s, h, c, block, n)
			if err != nil {
				return "", err
			}
			return fmt.Sprintf("due=%v", res.TotalDue), nil
		})
	}

	{
		c := fzCreators[rng.Intn(len(fzCreators))]
		payer := fzHolders[rng.Intn(len(fzHolders))]
		periods := uint64(1 + rng.Intn(3))
		paid := new(big.Int).Mul(big.NewInt(int64(periods)), big.NewInt(SubscriptionFee))
		add(fmt.Sprintf("renew:%s:%s:%d", c, payer, periods), func(s *MemStore, block uint64) (string, error) {
			return "", Renew(s, payer, c, block, periods, paid)
		})
	}

	{
		c := fzCreators[rng.Intn(len(fzCreators))]
		newFace := MinFace + int64(rng.Intn(1000))
		newCap := MinCap + int64(rng.Intn(100000)) + 1
		add(fmt.Sprintf("setface:%s:%d", c, newFace), func(s *MemStore, block uint64) (string, error) {
			return "", SetFace(s, c, c, block, newFace)
		})
		add(fmt.Sprintf("setcap:%s:%d", c, newCap), func(s *MemStore, block uint64) (string, error) {
			return "", SetCap(s, c, c, block, newCap)
		})
	}

	for i := 0; i < 2; i++ {
		c := fzCreators[rng.Intn(len(fzCreators))]
		from := fzHolders[rng.Intn(len(fzHolders))]
		to := fzHolders[rng.Intn(len(fzHolders))]
		if from == to {
			continue
		}
		amt := big.NewInt(int64(1 + rng.Intn(50)))
		id := fmt.Sprintf("xfer:%d:%s:%s:%s:%s", i, c, from, to, amt)
		add(id, func(s *MemStore, block uint64) (string, error) {
			return "", TransferCredits(s, from, c, from, to, block, amt)
		})
	}

	{
		c := fzCreators[rng.Intn(len(fzCreators))]
		h1 := fzHolders[rng.Intn(len(fzHolders))]
		h2 := fzHolders[rng.Intn(len(fzHolders))]
		pusher := fzHolders[rng.Intn(len(fzHolders))]
		if h1 != h2 {
			add(fmt.Sprintf("refundholder:%s:%s", c, h1), func(s *MemStore, block uint64) (string, error) {
				payout, err := RefundHolder(s, pusher, c, h1, block)
				return fmt.Sprintf("payout=%v", payout), err
			})
			add(fmt.Sprintf("refundholder:%s:%s", c, h2), func(s *MemStore, block uint64) (string, error) {
				payout, err := RefundHolder(s, pusher, c, h2, block)
				return fmt.Sprintf("payout=%v", payout), err
			})
		}
	}

	for _, ref := range w.pendingEscrows {
		ref := ref
		add(fmt.Sprintf("answer:%s:%d", ref.creator, ref.seq), func(s *MemStore, block uint64) (string, error) {
			res, err := Answer(s, ref.creator, ref.creator, block, ref.seq, "ans")
			return fmt.Sprintf("res=%+v", res), err
		})
		add(fmt.Sprintf("reclaim:%s:%d", ref.creator, ref.seq), func(s *MemStore, block uint64) (string, error) {
			res, err := Reclaim(s, ref.asker, ref.creator, block, ref.seq)
			return fmt.Sprintf("res=%+v", res), err
		})
	}

	return cands
}

func TestFuzzOrderingImmunity(t *testing.T) {
	const seed = int64(20260720003)
	const trials = 800
	rng := rand.New(rand.NewSource(seed))
	tr := &fzTrace{seed: seed}

	for trial := 0; trial < trials; trial++ {
		w := fzNewWorld()
		w.block = 1
		setupSteps := 20 + rng.Intn(60)
		for i := 0; i < setupSteps; i++ {
			fzApplyRandomAction(t, rng, w, tr)
		}
		block := w.block // the shared "given block" every candidate is tried at

		candidates := fzBuildOrderingCandidates(rng, w)
		if len(candidates) < 2 {
			continue
		}

		// Legality filter: keep only candidates individually legal against a
		// FRESH copy of the common starting snapshot.
		var legal []fzOpCandidate
		legalByID := map[string]bool{}
		for _, cand := range candidates {
			clone := fzCloneStore(w.s)
			if _, err := cand.apply(clone, block); err == nil {
				legal = append(legal, cand)
				legalByID[cand.id] = true
			}
		}

		// Direct I6 generalisation: an Answer and a Reclaim for the SAME
		// escrow must never BOTH be individually legal at the same block.
		for _, ref := range w.pendingEscrows {
			aID := fmt.Sprintf("answer:%s:%d", ref.creator, ref.seq)
			rID := fmt.Sprintf("reclaim:%s:%d", ref.creator, ref.seq)
			if legalByID[aID] && legalByID[rID] {
				tr.dump(t, 200)
				t.Fatalf("trial %d: I6 VIOLATED: both %s and %s are individually legal at block %d", trial, aID, rID, block)
			}
		}

		if len(legal) < 2 {
			continue
		}
		n := len(legal)
		if n > 4 {
			n = 4
		}
		idxs := rng.Perm(len(legal))[:n]
		subset := make([]fzOpCandidate, n)
		subsetIDs := make([]string, n)
		for i, idx := range idxs {
			subset[i] = legal[idx]
			subsetIDs[i] = legal[idx].id
		}

		type permResult struct {
			outcomeKey string
			dump       string
		}
		byOutcome := map[string][]permResult{}

		for _, perm := range fzPermutations(n) {
			clone := fzCloneStore(w.s)
			var succeeded []string
			for _, pidx := range perm {
				op := subset[pidx]
				effect, err := op.apply(clone, block)
				if err == nil {
					// Include the EFFECT, not just the id: a RefundHolder
					// that no-op'd (payout=0) and one that paid out real
					// value are different outcomes even though both return
					// err==nil (RefundHolder's own doc: a zero balance is "a
					// harmless no-op: (0, nil)") — conflating them would
					// compare permutations that did genuinely different
					// things and call any difference a false "violation".
					succeeded = append(succeeded, op.id+"["+effect+"]")
				}
			}
			sort.Strings(succeeded)
			outcomeKey := strings.Join(succeeded, ",")
			// Order-invariant money state + the two aggregates whose
			// per-key distribution is order-dependent by design (see
			// fzOrderInvariantDump for the full justification).
			dump := fzOrderInvariantDump(clone) + "\n" + fzOrderAggregates(clone)
			byOutcome[outcomeKey] = append(byOutcome[outcomeKey], permResult{outcomeKey: outcomeKey, dump: dump})

			// Whatever DID succeed in this permutation must still leave the
			// system internally consistent — catches accounting corruption
			// even in the documented "order-dependent success" case.
			fzCheckInvariantsOnStore(t, clone, tr, fmt.Sprintf("trial %d perm %v", trial, perm), fzEscrowedSnapshot(clone))
		}

		for outcome, group := range byOutcome {
			first := group[0].dump
			for gi := 1; gi < len(group); gi++ {
				if group[gi].dump != first {
					tr.dump(t, 200)
					t.Fatalf("trial %d: ORDERING NOT IMMUNE: op set %v — the SAME ops succeeded (%s) in every order, but final state differs by permutation.\n--- state A ---\n%s\n--- state B ---\n%s",
						trial, subsetIDs, outcome, first, group[gi].dump)
				}
			}
		}
		if len(byOutcome) > 1 {
			var keys []string
			for k := range byOutcome {
				keys = append(keys, k)
			}
			sort.Strings(keys)
			tr.add("trial %d: op set %v has ORDER-DEPENDENT SUCCESS (documented, intended: resource contention, not an I6 violation) — outcome groups: %v", trial, subsetIDs, keys)
		}
	}
	t.Logf("TestFuzzOrderingImmunity: %d trials passed (seed=%d), subsets up to size 4 (<=24 permutations each)", trials, seed)
}

// ===========================================================================
// Property #4 — ROUNDING (must always favour the reserve)
// ===========================================================================

func TestFuzzRoundingFavorsReserve(t *testing.T) {
	t.Run("PegNeverLeaksThroughAwkwardTinyOps", func(t *testing.T) {
		const seed = int64(20260720004)
		const steps = 30000
		rng := rand.New(rand.NewSource(seed))
		w := fzNewWorld()
		w.block = 1
		tr := &fzTrace{seed: seed}

		for i := 0; i < steps; i++ {
			switch rng.Intn(4) {
			case 0, 1: // heavily bias toward 1-TOKEN buy/sell/refund churn —
				// the adversarially tiny ops where an off-by-one in the
				// area floor would show up first
				c := fzCreators[rng.Intn(len(fzCreators))]
				h := fzHolders[rng.Intn(len(fzHolders))]
				if getU64(w.s, kRegisteredAt(c)) == 0 {
					fzActRegister(t, rng, w, tr)
				}
				switch rng.Intn(3) {
				case 0:
					res, err := Buy(w.s, h, c, w.block, big.NewInt(1))
					if err == nil {
						tr.add("tiny Buy(%s,%s,1) -> due=%v", h, c, res.TotalDue)
						w.pay(h, res.TotalDue)
					} else {
						tr.add("tiny Buy(%s,%s,1) -> err=%v", h, c, err)
					}
				case 1:
					res, err := Sell(w.s, h, c, w.block, big.NewInt(1))
					if err == nil {
						tr.add("tiny Sell(%s,%s,1) -> net=%v", h, c, res.Net)
						w.receive(h, res.Net)
					} else {
						tr.add("tiny Sell(%s,%s,1) -> err=%v", h, c, err)
					}
				default:
					payout, err := Refund(w.s, h, c, w.block, big.NewInt(1))
					tr.add("tiny Refund(%s,%s,1) -> payout=%v err=%v", h, c, payout, err)
					if err == nil {
						w.receive(h, payout)
						w.refunded[c] = true
					}
				}
			default:
				fzApplyRandomAction(t, rng, w, tr)
			}
			// This subtest hunts for rounding/dust leaks (property #4), not
			// authorization gaps (property #2's job) — fzApplyRandomAction's
			// TransferCredits action can legitimately move credits to an
			// unrelated holder (see TestFuzzNoFreeMoney's dedicated finding),
			// which would trip a bundled no-free-money check for a reason
			// entirely outside this subtest's scope. fzCheckSolvencyCore is
			// exactly property #1/#4's shared PEG+I3+I1+global-identity gate.
			fzCheckSolvencyCore(t, w, tr, i)
		}
		t.Logf("PegNeverLeaksThroughAwkwardTinyOps: %d steps of adversarially tiny ops, zero dust throughout (seed=%d)", steps, seed)
	})

	t.Run("AskCreditsAlwaysCeilsNeverShortchangesReserve", func(t *testing.T) {
		const seed = int64(20260720005)
		const iterations = 20000
		rng := rand.New(rand.NewSource(seed))

		for i := 0; i < iterations; i++ {
			s := NewMemStore()
			creator := fmt.Sprintf("fzrndcr%d", i%50)
			asker := "fzrndask"
			const regBlock = uint64(1000)
			// RULING C re-shape of this sweep: the fixture is a REAL curve
			// market at S = 5000 (Buy below), and settlement now enforces the
			// C4/C5/depth/spend guards, so the swept (face, rate) pairs are
			// drawn from the coherent region instead of the whole plane:
			//   avg  = ceil(Area(5000)/5000) = 42,574 (real reserve, C5)
			//   rate ∈ [ceil(avg/4) = 10,644, min(2·face, spot(5000)=106,000)]
			//          (lower: C5 tripwire; upper: C4 min-price + the spot arm
			//          of min(), so RateUsed == the seeded marker exactly)
			//   rate >= ceil(face/250) so c = ceil(face/rate) <= 250 = S/20,
			//          the 5%%-of-supply spend cap
			//   face ∈ [5,322, MaxFace) (face·2 >= the smallest legal rate)
			// The sub-500 rates the old sweep also hit are NOT lost coverage
			// on the ceiling property itself — TestCreditsForAskCeilsNotFloors
			// and the pure-math paths cover those; THIS test's subject is the
			// end-to-end wiring through Ask, which now legitimately refuses
			// incoherent (face, rate) combinations by design.
			// 5322 was the smallest face that could clear the C4 floor at the
			// lowest rate this sweep generates. USER RULING 2026-07-27 made the
			// posted face a GROSS price, of which only ~88% is the token leg
			// C4 actually measures, so the smallest legal POSTED face grosses
			// up to 6047 (6047-floor(6047*1200/10000) = 6047-725 = 5322; 6046
			// yields 5321 and is refused). Generating below this would make the
			// rate range empty, not test anything weaker.
			face := int64(6047) + rng.Int63n(MaxFace-6047)
			if err := Register(s, creator, creator, regBlock, face, MaxCap); err != nil {
				t.Fatalf("iter %d: setup Register: %v", i, err)
			}
			// Fund the asker on the CURVE (Buy is the only issuance path):
			// 5000 tokens covers the worst-case spend the cap admits (250).
			if _, err := Buy(s, asker, creator, regBlock, big.NewInt(5000)); err != nil {
				t.Fatalf("iter %d: setup Buy: %v", i, err)
			}

			loRate := int64(10_644)
			if byCap := (face + 249) / 250; byCap > loRate {
				loRate = byCap
			}
			// C4 binds on the TOKEN LEG, not the posted face (settlement.go's
			// settlePosted): the legal ceiling is rate <= 2*tokenLeg, so this
			// bound is computed from the leg. Using 2*face here would generate
			// pairs the contract must legitimately refuse and read the refusal
			// as a rounding bug.
			hiRate := 2 * (face - (face*1200)/10000)
			if hiRate > 106_000 {
				hiRate = 106_000
			}
			if hiRate < loRate {
				t.Fatalf("iter %d: sweep bug: empty rate range for face=%d", i, face)
			}
			rate := big.NewInt(loRate + rng.Int63n(hiRate-loRate+1))

			// Seed a constant-rate history into BOTH rings (seedSettleObs,
			// ask_test.go — it clears the funding Buy's own curve-fed
			// observations first) so Ask's internal settlement derivation
			// legitimately returns exactly `rate`, preserving this test's
			// original job: exercising creditsForAsk's ceiling across a wide
			// range of rates.
			askBlock := seedSettleObs(s, creator, regBlock+10, rate)

			owed := commissionOwedFor(big.NewInt(face))
			// USER RULING 2026-07-27: the posted face is the buyer's TOTAL, so
			// only face minus the commission settles in tokens. Recomputed here
			// from first principles (not via splitFace) so this stays an
			// INDEPENDENT model of what the contract should charge.
			tokenLeg := new(big.Int).Sub(big.NewInt(face), owed)
			maxCredits := fzCeilDiv(tokenLeg, rate) // the asker's own cap == the exact expected spend
			res, err := askAt0(s, asker, creator, askBlock, maxCredits, owed, "cid", MinAskDeadline)
			if err != nil {
				t.Fatalf("iter %d: Ask(face=%d rate=%s): %v", i, face, rate, err)
			}
			if res.RateUsed.Cmp(rate) != 0 {
				t.Fatalf("iter %d: RateUsed = %s, want the seeded TWAP %s (min(short,long,spot) did not resolve to the marker)", i, res.RateUsed, rate)
			}

			want := fzCeilDiv(tokenLeg, rate)
			if res.CreditsSpent.Cmp(want) != 0 {
				t.Fatalf("iter %d: ROUNDING VIOLATION: face=%d (tokenLeg=%s) rate=%s got CreditsSpent=%s, independent ceil(tokenLeg/rate)=%s",
					i, face, tokenLeg, rate, res.CreditsSpent, want)
			}
			// The buyer's two legs must re-sum to the posted face EXACTLY —
			// the whole point of the ruling. No dust may be created or lost by
			// the split at any face in the fuzzed range.
			if sum := new(big.Int).Add(tokenLeg, owed); sum.Cmp(big.NewInt(face)) != 0 {
				t.Fatalf("iter %d: SPLIT LOST VALUE: tokenLeg=%s + commission=%s = %s, want face=%d",
					i, tokenLeg, owed, sum, face)
			}
			// The defining ceiling property, checked directly: spending one
			// FEWER credit must always undershoot face.
			oneLess := new(big.Int).Sub(res.CreditsSpent, big.NewInt(1))
			if oneLess.Sign() > 0 {
				got := new(big.Int).Mul(oneLess, rate)
				if got.Cmp(tokenLeg) >= 0 {
					t.Fatalf("iter %d: CreditsSpent=%s is not minimal for tokenLeg=%s at rate=%s: one less (%s) still covers it (%s)",
						i, res.CreditsSpent, tokenLeg, rate, oneLess, got)
				}
			}
			covered := new(big.Int).Mul(res.CreditsSpent, rate)
			if covered.Cmp(tokenLeg) < 0 {
				t.Fatalf("iter %d: RESERVE SHORTCHANGED: CreditsSpent=%s * rate=%s = %s < tokenLeg=%s (face=%d)", i, res.CreditsSpent, rate, covered, tokenLeg, face)
			}
		}
		t.Logf("AskCreditsAlwaysCeilsNeverShortchangesReserve: %d randomized (face,rate) pairs, all ceil-exact (seed=%d)", iterations, seed)
	})

	t.Run("TwapFloorMatchesIndependentModel", func(t *testing.T) {
		const seed = int64(20260720006)
		const iterations = 5000
		rng := rand.New(rand.NewSource(seed))

		for i := 0; i < iterations; i++ {
			s := NewMemStore()
			creator := fmt.Sprintf("fztwapcr%d", i%50)
			block := uint64(10_000_000)

			n := int(MinObsCount) + rng.Intn(int(ObsWindow)-int(MinObsCount)+1)
			b := block - MinObsBlocks - uint64(rng.Intn(2000))
			for j := 0; j < n; j++ {
				b += uint64(1 + rng.Intn(300))
				if b > block {
					b = block
				}
				RecordObs(s, creator, b, fzRateLikePositive(rng))
			}

			got, err := AskRate(s, creator, block)
			if err != nil {
				continue // insufficient span/deviation on this draw — not this sub-check's target
			}

			// Independently re-derive the SAME weighted-average-with-clamp
			// algorithm twap.go documents, reading back the REAL ring-buffer
			// contents (so post-dedup reality is what's modelled, not this
			// loop's own possibly-diverged local record) via readTwapObs —
			// the storage primitive, not the weighting logic under test.
			nObs := getU64(s, kObsIdx(creator))
			count := nObs
			if count > ObsWindow {
				count = ObsWindow
			}
			startSeq := uint64(0)
			if nObs > ObsWindow {
				startSeq = nObs - ObsWindow
			}
			var pts []twapObs
			for seq := startSeq; seq < nObs; seq++ {
				o, ok := readTwapObs(s, creator, seq%ObsWindow)
				if !ok {
					t.Fatalf("iter %d: could not read back observation seq=%d", i, seq)
				}
				pts = append(pts, o)
			}

			weighted := big.NewInt(0)
			totalW := uint64(0)
			for j, p := range pts {
				var w uint64
				if j == len(pts)-1 {
					w = block - p.block
				} else {
					w = pts[j+1].block - p.block
				}
				if w > MaxObsWeightBlocks {
					w = MaxObsWeightBlocks
				}
				totalW += w
				weighted = mAdd(weighted, new(big.Int).Mul(p.rate, new(big.Int).SetUint64(w)))
			}
			if totalW == 0 {
				continue
			}
			wantFloor := new(big.Int).Div(weighted, new(big.Int).SetUint64(totalW))
			if got.Cmp(wantFloor) != 0 {
				t.Fatalf("iter %d: TWAP FLOOR MISMATCH: independent floor(Σrate*w/Σw)=%s, AskRate returned %s (Σweighted=%s Σw=%d)",
					i, wantFloor, got, weighted, totalW)
			}
			// Rounding favours the reserve: a floored rate is <= the true
			// weighted average, so ceil(face/rate) can only ever demand MORE
			// credits than the unrounded rate would — never fewer.
			check := new(big.Int).Mul(got, new(big.Int).SetUint64(totalW))
			if check.Cmp(weighted) > 0 {
				t.Fatalf("iter %d: twap*totalW=%s > Σweighted=%s — floor rounded UP, not down (favors the asker, not the reserve)", i, check, weighted)
			}
		}
		t.Logf("TwapFloorMatchesIndependentModel: %d randomized observation windows cross-checked against an independent model (seed=%d)", iterations, seed)
	})
}

// ===========================================================================
// Property #5 — BOUNDARY SWEEP (min, max, min-1, max+1, 0, 1, huge)
// ===========================================================================

func TestFuzzBoundarySweep(t *testing.T) {
	const seed = int64(20260720007)
	const iterations = 20000
	rng := rand.New(rand.NewSource(seed))

	pick := func(lo, hi int64) int64 {
		opts := []int64{lo - 1, lo, lo + 1, hi - 1, hi, hi + 1, 0, 1}
		if hi < (int64(1) << 60) {
			opts = append(opts, hi*1000)
		}
		return opts[rng.Intn(len(opts))]
	}
	expectSym := func(t *testing.T, label string, lo, hi, v int64, err error, wantSymOutOfBand string) {
		t.Helper()
		inBand := v >= lo && v <= hi
		if inBand && err != nil {
			t.Fatalf("%s: v=%d is INSIDE documented bound [%d,%d] but was REJECTED: %v", label, v, lo, hi, err)
		}
		if !inBand {
			if err == nil {
				t.Fatalf("%s: v=%d is OUTSIDE documented bound [%d,%d] but was ACCEPTED", label, v, lo, hi)
			}
			if sym := fzErrSym(err); sym != wantSymOutOfBand {
				t.Fatalf("%s: v=%d OUTSIDE [%d,%d] correctly rejected but with symbol %q, want %q: %v", label, v, lo, hi, sym, wantSymOutOfBand, err)
			}
		}
	}

	for i := 0; i < iterations; i++ {
		switch rng.Intn(9) {
		case 0: // Register.face
			s := NewMemStore()
			creator := fmt.Sprintf("fzbfc%d", i)
			v := pick(MinFace, MaxFace)
			err := Register(s, creator, creator, 100, v, MaxCap)
			expectSym(t, "Register.face", MinFace, MaxFace, v, err, ErrInput)

		case 1: // Register.cap
			s := NewMemStore()
			creator := fmt.Sprintf("fzbcc%d", i)
			v := pick(MinCap, MaxCap)
			err := Register(s, creator, creator, 100, MinFace, v)
			expectSym(t, "Register.cap", MinCap, MaxCap, v, err, ErrInput)

		case 2: // SetFace bounds. NOTE: the 2x band applies on EVERY path — a
			// window that has elapsed refreshes the anchor, it does not lift the
			// limit. (This case previously asserted the opposite, which was the
			// bug an exploiter scrutinizer traced to a creator sandwiching their
			// own askers by stacking SetFace calls ahead of a pending ask.) So
			// the live bound here is the intersection of [MinFace,MaxFace] with
			// the band around the registered face.
			s := NewMemStore()
			creator := fmt.Sprintf("fzbsf%d", i)
			const startFace = int64(1000)
			if err := Register(s, creator, creator, 100, startFace, MaxCap); err != nil {
				t.Fatalf("setup: %v", err)
			}
			lo := startFace / int64(FaceBandNumerator)
			hi := startFace * int64(FaceBandNumerator)
			if lo < MinFace {
				lo = MinFace
			}
			if hi > MaxFace {
				hi = MaxFace
			}
			v := pick(lo, hi)
			err := SetFace(s, creator, creator, 100+FaceBandWindow+1, v)
			expectSym(t, "SetFace (band around anchor)", lo, hi, v, err, ErrInput)

		case 3: // SetCap, supply==0 so [MinCap,MaxCap] is the only live bound
			s := NewMemStore()
			creator := fmt.Sprintf("fzbsc%d", i)
			if err := Register(s, creator, creator, 100, 1000, MaxCap); err != nil {
				t.Fatalf("setup: %v", err)
			}
			v := pick(MinCap, MaxCap)
			err := SetCap(s, creator, creator, 100, v)
			expectSym(t, "SetCap", MinCap, MaxCap, v, err, ErrInput)

		case 4: // Ask.deadlineBlocks — every other parameter fixed comfortably in-range
			s := NewMemStore()
			creator := fmt.Sprintf("fzbad%d", i)
			// RULING C: the PAR fallback is gone, so the in-range side of
			// this boundary needs a market that can actually PRICE — the
			// canonical S=5000 / face 10,000 / marker 15,000 fixture (see
			// the ceil sweep above for the guard math). The subtest's
			// subject is still ONLY the deadline band.
			if err := Register(s, creator, creator, 100, 10_000, MaxCap); err != nil {
				t.Fatalf("setup: %v", err)
			}
			if _, err := Buy(s, "fzbadasker", creator, 100, big.NewInt(5000)); err != nil {
				t.Fatalf("setup: %v", err)
			}
			askBlock := seedSettleObs(s, creator, 110, big.NewInt(15_000))
			v := pick(int64(MinAskDeadline), int64(MaxAskDeadline))
			deadline := uint64(v)
			if v < 0 {
				deadline = 0
			}
			owed := commissionOwedFor(big.NewInt(10_000))
			_, err := askAt0(s, "fzbadasker", creator, askBlock, big.NewInt(1_000_000), owed, "cid", deadline)
			inBand := deadline >= MinAskDeadline && deadline <= MaxAskDeadline
			if inBand && err != nil {
				t.Fatalf("Ask.deadline: v=%d INSIDE [%d,%d] but rejected: %v", deadline, MinAskDeadline, MaxAskDeadline, err)
			}
			if !inBand {
				if err == nil {
					t.Fatalf("Ask.deadline: v=%d OUTSIDE [%d,%d] but accepted", deadline, MinAskDeadline, MaxAskDeadline)
				}
				if sym := fzErrSym(err); sym != ErrInput {
					t.Fatalf("Ask.deadline: v=%d OUTSIDE bound, rejected with symbol %q, want %q: %v", deadline, sym, ErrInput, err)
				}
			}

		case 5: // Renew.periods
			s := NewMemStore()
			creator := fmt.Sprintf("fzbrp%d", i)
			if err := Register(s, creator, creator, 100, 1000, MaxCap); err != nil {
				t.Fatalf("setup: %v", err)
			}
			// Register itself already grants ONE free SubscriptionPeriod
			// (kPaidUntil = block+SubscriptionPeriod), so a Renew attempted
			// AT the registration block only has [1, MaxPrepaidPeriods-1] of
			// real headroom before "extension exceeds MaxPrepaidPeriods ahead
			// of now" fires — that guard is a SEPARATE, correct rejection,
			// not the [1,MaxPrepaidPeriods] bound this case sweeps. Renewing
			// exactly AT paidUntil (base==block, no pre-existing headroom
			// consumed) isolates the periods bound cleanly.
			renewBlock := uint64(100) + SubscriptionPeriod
			v := pick(1, int64(MaxPrepaidPeriods))
			periods := uint64(v)
			if v < 0 {
				periods = 0
			}
			paid := new(big.Int).Mul(big.NewInt(int64(periods)), big.NewInt(SubscriptionFee))
			err := Renew(s, "fzbrpayer", creator, renewBlock, periods, paid)
			inBand := periods >= 1 && periods <= MaxPrepaidPeriods
			if inBand && err != nil {
				t.Fatalf("Renew.periods: v=%d INSIDE [1,%d] but rejected: %v", periods, MaxPrepaidPeriods, err)
			}
			if !inBand {
				if err == nil {
					t.Fatalf("Renew.periods: v=%d OUTSIDE [1,%d] but accepted", periods, MaxPrepaidPeriods)
				}
				if sym := fzErrSym(err); sym != ErrInput {
					t.Fatalf("Renew.periods: v=%d OUTSIDE bound, rejected with symbol %q, want %q: %v", periods, sym, ErrInput, err)
				}
			}

		case 6: // Buy.n — 0/1/huge, no protocol ceiling besides the market cap
			s := NewMemStore()
			creator := fmt.Sprintf("fzbpa%d", i)
			if err := Register(s, creator, creator, 100, 1000, MaxCap); err != nil {
				t.Fatalf("setup: %v", err)
			}
			amt := fzAmount(rng)
			_, err := Buy(s, "fzbpaholder", creator, 100, amt)
			positiveWithinCap := amt != nil && amt.Sign() > 0 && amt.Cmp(big.NewInt(MaxCap)) <= 0
			if positiveWithinCap && err != nil {
				t.Fatalf("Buy: n=%s positive and within cap=%d but rejected: %v", amt, MaxCap, err)
			}
			if (amt == nil || amt.Sign() <= 0) && err == nil {
				t.Fatalf("Buy: n=%v accepted despite being <= 0", amt)
			}
			if positiveWithinCap && err == nil {
				// The cap is denominated in TOKENS under the curve (money-math
				// §8.5): a within-cap buy always succeeds regardless of the HBD
				// cost, because the wrapper's draw — not core — bounds spend.
				if got := getMoney(s, kSupply(creator)); got.Cmp(amt) != 0 {
					t.Fatalf("Buy: n=%s minted supply %s", amt, got)
				}
			}

		case 7: // TransferCredits.amount against a funded holder
			s := NewMemStore()
			creator := fmt.Sprintf("fzbtc%d", i)
			if err := Register(s, creator, creator, 100, 1000, MaxCap); err != nil {
				t.Fatalf("setup: %v", err)
			}
			if _, err := Buy(s, "fzbtcfrom", creator, 100, big.NewInt(1000)); err != nil {
				t.Fatalf("setup: %v", err)
			}
			amt := fzAmount(rng)
			err := TransferCredits(s, "fzbtcfrom", creator, "fzbtcfrom", "fzbtcto", 100, amt)
			validAmt := amt != nil && amt.Sign() > 0 && amt.Cmp(big.NewInt(1000)) <= 0
			if validAmt && err != nil {
				t.Fatalf("TransferCredits: amt=%s valid and within balance=1000 but rejected: %v", amt, err)
			}
			if !validAmt && err == nil {
				t.Fatalf("TransferCredits: amt=%v invalid/over-balance but accepted", amt)
			}

		default: // 8: Refund.credits against a funded holder
			s := NewMemStore()
			creator := fmt.Sprintf("fzbrf%d", i)
			if err := Register(s, creator, creator, 100, 1000, MaxCap); err != nil {
				t.Fatalf("setup: %v", err)
			}
			if _, err := Buy(s, "fzbrfholder", creator, 100, big.NewInt(1000)); err != nil {
				t.Fatalf("setup: %v", err)
			}
			// WIND-DOWN BLOCK: Refund is phase-routed to FROZEN/CLOSED
			// (refund.go's rail reconciliation — Sell is the ACTIVE exit).
			// This case sweeps the CREDITS bound, so it must be run at a
			// block where the rail is actually open, or every draw would
			// reject on the phase instead.
			// A1 (2026-08-30): a lapse no longer opens the Refund rail; Retire does.
			if err := Retire(s, creator, creator, uint64(100)+SubscriptionPeriod+GraceBlocks); err != nil {
				t.Fatalf("setup: Retire: %v", err)
			}
			wdBlock := uint64(100) + SubscriptionPeriod + GraceBlocks + 1
			amt := fzAmount(rng)
			_, err := Refund(s, "fzbrfholder", creator, wdBlock, amt)
			validAmt := amt != nil && amt.Sign() > 0 && amt.Cmp(big.NewInt(1000)) <= 0
			if validAmt && err != nil {
				t.Fatalf("Refund: credits=%s valid and within balance=1000 but rejected: %v", amt, err)
			}
			if !validAmt && err == nil {
				t.Fatalf("Refund: credits=%v invalid/over-balance but accepted", amt)
			}
		}
	}
	t.Logf("TestFuzzBoundarySweep: %d randomized boundary-biased iterations passed (seed=%d)", iterations, seed)
}

// fzErrSym mirrors the errSymbol/askErrSymbol helpers already declared
// elsewhere in this package's test files — redeclared here under the fz
// prefix per this file's ownership rule, not reused from a sibling file.
func fzErrSym(err error) string {
	if e, ok := err.(*Err); ok {
		return e.Symbol
	}
	return ""
}
