package indexer

// scenario_test.go — the canonical creator-market event sequence shared by
// index_test.go and api_test.go, so every test asserting against it is
// checking the exact same fixture. Every JSON line below is hand-written to
// match ../core/events.go's Ev* constructors' exact wire shape byte for
// byte (field names, field order, quoting) — see events_test.go's
// TestEv* suite, which independently proves the real constructors produce
// this shape. Keeping this fixture hand-written (not generated by calling
// core.Ev* directly) matches this package's own "standalone consumer of the
// LOG FORMAT" boundary discipline (events.go's file doc) — indexer_test
// code never imports creator-tokens/core.
//
// The scenario, creator "alice", in emission order (see the doc comment
// above each push below for what each line does to running state):
//
//	block 100   registered  alice/alice          face=1000  cap=100000  feePaid=10000
//	block 200   prepaid     alice/bob             hbdPaid=5000   -> bob=5000
//	block 210   prepaid     alice/carol            hbdPaid=3000   -> carol=3000
//	block 220   transferred alice/bob->dave        amount=1000     -> bob=4000 dave=1000
//	block 300   asked       alice/bob   seq0        creditsSpent=500  -> bob=3500, escrow0 open
//	block 350   answered    alice/alice seq0        creditsToCreator=500 commissionHbd=120 -> alice=500, escrow0 KEPT (response 50)
//	block 400   asked       alice/carol seq1        creditsSpent=300  -> carol=2700, escrow1 open
//	block 430000 reclaimed  alice/carol seq1        credits=300 commissionHbd=100 -> carol=3000, escrow1 MISSED
//	block 500   asked       alice/dave  seq2        creditsSpent=200  -> dave=800, escrow2 open
//	block 540   answered    alice/alice seq2        creditsToCreator=200 commissionHbd=80 -> alice=700, escrow2 KEPT (response 40)
//	block 600   asked       alice/bob   seq3        creditsSpent=150  -> bob=3350, escrow3 open, NEVER resolved (pending)
//	block 700   refunded    alice/carol             credits=1000 payout=950 -> carol=2000
//	block 800   refundPushed alice/keeper1->dave    creditsBurned=800 payout=760 -> dave=0
//	block 900   faceChanged alice/alice             1000->1500
//	block 950   capChanged  alice/alice             100000->200000
//	block 1000  renewed     alice/fan1              periods=1 paid=10000
//
// Final expected state: alice=700 bob=3350 carol=2000 dave=0 (excluded from
// HolderList — zero balance). AnsweredCount=2 MissedCount=1 PendingCount=1.
// ResponseBlocks=[50,40] in resolution order (seq0 resolves before seq2).
// DistinctAskers=3 (bob, carol, dave — none of the three resolved asks is a
// self-deal: alice, the creator, never asks herself) SelfDealtExcluded=0
// (M1). TreasuryHbd contribution from this scenario alone (M4, Index-wide,
// not asserted per-market here): feePaid 10000 + renewed paid 10000 +
// commissionHbd 120 (seq0 answered) + commissionHbd 80 (seq2 answered) =
// 20200; ReclaimOutflowHbd contribution: commissionHbd 100 (seq1 reclaimed).
func buildCanonicalScenario() *MockEventSource {
	src := NewMockEventSource()
	src.Push(`{"ev":"registered","v":1,"creator":"alice","actor":"alice","block":100,"face":"1000","cap":"100000","feePaid":"10000"}`)
	src.Push(`{"ev":"prepaid","v":1,"creator":"alice","actor":"bob","block":200,"hbdPaid":"5000","creditsMinted":"5000"}`)
	src.Push(`{"ev":"prepaid","v":1,"creator":"alice","actor":"carol","block":210,"hbdPaid":"3000","creditsMinted":"3000"}`)
	src.Push(`{"ev":"transferred","v":1,"creator":"alice","actor":"bob","block":220,"to":"dave","amount":"1000"}`)
	src.Push(`{"ev":"asked","v":1,"creator":"alice","actor":"bob","block":300,"seq":0,"creditsSpent":"500","commissionHbd":"120","rate":"1000000","deadlineBlocks":28800,"contentHash":"q1"}`)
	src.Push(`{"ev":"answered","v":1,"creator":"alice","actor":"alice","block":350,"seq":0,"creditsToCreator":"500","commissionHbd":"120","answerHash":"a1"}`)
	src.Push(`{"ev":"asked","v":1,"creator":"alice","actor":"carol","block":400,"seq":1,"creditsSpent":"300","commissionHbd":"100","rate":"900000","deadlineBlocks":28800,"contentHash":"q2"}`)
	src.Push(`{"ev":"reclaimed","v":1,"creator":"alice","actor":"carol","block":430000,"seq":1,"credits":"300","commissionHbd":"100"}`)
	src.Push(`{"ev":"asked","v":1,"creator":"alice","actor":"dave","block":500,"seq":2,"creditsSpent":"200","commissionHbd":"80","rate":"1100000","deadlineBlocks":28800,"contentHash":"q3"}`)
	src.Push(`{"ev":"answered","v":1,"creator":"alice","actor":"alice","block":540,"seq":2,"creditsToCreator":"200","commissionHbd":"80","answerHash":"a3"}`)
	src.Push(`{"ev":"asked","v":1,"creator":"alice","actor":"bob","block":600,"seq":3,"creditsSpent":"150","commissionHbd":"60","rate":"1000000","deadlineBlocks":28800,"contentHash":"q4"}`)
	src.Push(`{"ev":"refunded","v":1,"creator":"alice","actor":"carol","block":700,"credits":"1000","payout":"950"}`)
	src.Push(`{"ev":"refundPushed","v":1,"creator":"alice","actor":"keeper1","block":800,"holder":"dave","creditsBurned":"800","payout":"760"}`)
	src.Push(`{"ev":"faceChanged","v":1,"creator":"alice","actor":"alice","block":900,"oldFace":"1000","newFace":"1500"}`)
	src.Push(`{"ev":"capChanged","v":1,"creator":"alice","actor":"alice","block":950,"oldCap":"100000","newCap":"200000"}`)
	src.Push(`{"ev":"renewed","v":1,"creator":"alice","actor":"fan1","block":1000,"periods":1,"paid":"10000"}`)
	return src
}
