'use client';

import Big from 'big.js';
import { Gift } from 'lucide-react';
import { Icons } from '@ui/components/icons';
import { useTranslation } from '@/blog/i18n/client';
import DelegateDialog from './dialogs/delegate-dialog';
import ConvertDialog from './dialogs/convert-dialog';
import RecurringTransferDialog from './dialogs/recurring-transfer-dialog';
import ClaimAccountDialog from './dialogs/claim-account-dialog';

const CARD_CLASS = 'rounded-panel border border-line-9 bg-surface-1 p-5';
// W-3: was rounded-control. Rows are 14px.
const ROW_CLASS =
  'flex w-full items-center gap-[11px] rounded-card px-2 py-2.5 text-left text-ink-4 transition-colors hover:bg-surface-16';
const ICON_WRAP_CLASS =
  'flex h-[30px] w-[30px] shrink-0 items-center justify-center rounded-control bg-surface-23 text-ink-8';

function RowLabel({ label, sub }: { label: string; sub: string }) {
  return (
    <span className="min-w-0 flex-1">
      <span className="block text-[14px] leading-[22px] font-medium">{label}</span>
      <span className="block text-caption text-ink-14">{sub}</span>
    </span>
  );
}

/**
 * Power-user tools rail card. Every row opens a real dialog wired to a real
 * op (Delegate HP / Convert / Recurring transfers / Claim account tokens) or
 * jumps to the on-page Savings Vault section. "Claim account tokens" mints a
 * token (`claim_account_operation`, burns RC); spending a token to create a
 * new account is a separate, still-unbuilt op — see claim-account-dialog.tsx.
 */
export default function AdvancedToolsCard({
  username,
  maxHp,
  liquidHive,
  liquidHbd,
  pendingClaimedAccounts
}: {
  username: string;
  /**
   * ★ MOVABLE HP, not effective (2026-08-13, map item 10). `wallet-derived.ts`
   * states the rule directly: `netHp` includes HP delegated IN, which cannot
   * be re-delegated because it belongs to the delegator. Delegate used to be
   * passed `netHp` under this same prop name (also called `netHp`), which
   * printed a MOVABLE balance of "Balance: 200.053" on a tester account whose
   * actually-delegatable stake was ~0, with Use-Max filling in a value the
   * chain was always going to reject. Renamed from `netHp` to `maxHp` so the
   * prop name states what every caller must supply, matching the rename
   * PowerDownDialog already needed for the same reason.
   */
  maxHp: Big;
  liquidHive: Big;
  liquidHbd: Big;
  pendingClaimedAccounts: number;
}) {
  const { t } = useTranslation('common_blog');

  return (
    <div className={CARD_CLASS} data-testid="wallet-advanced-card">
      <div className="mb-1 flex items-center gap-2">
        {/* ★ W-9: this was a hand-drawn four-point sparkle. A sparkle means
            "generated by a model" to anyone who has used software in the last
            two years, and it meant nothing about the card it sat on: this is a
            list of manual controls (delegate, convert, schedule a transfer).
            Sliders say "settings you operate yourself", which is what it is. */}
        <Icons.settings className="h-4 w-4 text-ink-10" aria-hidden />
        <span className="text-[16px] leading-[24px] font-semibold text-ink-2">{t('wallet.advanced.title')}</span>
      </div>
      <p className="mb-3.5 font-ui text-caption text-ink-14">{t('wallet.advanced.description')}</p>

      <div className="flex flex-col gap-0.5">
        <DelegateDialog
          username={username}
          maxHp={maxHp}
          trigger={
            <button type="button" className={ROW_CLASS} data-testid="wallet-advanced-delegate">
              <span className={ICON_WRAP_CLASS}>
                <Icons.userPlus className="h-4 w-4" />
              </span>
              <RowLabel label={t('wallet.advanced.delegate.label')} sub={t('wallet.advanced.delegate.sub')} />
              <Icons.chevronRight className="h-[15px] w-[15px] shrink-0 text-ink-21" />
            </button>
          }
        />

        <ClaimAccountDialog
          username={username}
          pendingClaimedAccounts={pendingClaimedAccounts}
          trigger={
            <button type="button" className={ROW_CLASS} data-testid="wallet-advanced-claim-account">
              <span className={ICON_WRAP_CLASS}>
                <Gift className="h-4 w-4" />
              </span>
              <RowLabel
                label={t('wallet.advanced.claim_account.label')}
                sub={t('wallet.advanced.claim_account.sub')}
              />
              <Icons.chevronRight className="h-[15px] w-[15px] shrink-0 text-ink-21" />
            </button>
          }
        />

        <ConvertDialog
          username={username}
          hbdBalance={liquidHbd}
          trigger={
            <button type="button" className={ROW_CLASS} data-testid="wallet-advanced-convert">
              <span className={ICON_WRAP_CLASS}>
                <Icons.swap className="h-4 w-4" />
              </span>
              <RowLabel label={t('wallet.advanced.convert.label')} sub={t('wallet.advanced.convert.sub')} />
              <Icons.chevronRight className="h-[15px] w-[15px] shrink-0 text-ink-21" />
            </button>
          }
        />

        <RecurringTransferDialog
          username={username}
          liquidHive={liquidHive}
          liquidHbd={liquidHbd}
          trigger={
            <button type="button" className={ROW_CLASS} data-testid="wallet-advanced-recurring">
              <span className={ICON_WRAP_CLASS}>
                <Icons.swap className="h-4 w-4" />
              </span>
              <RowLabel label={t('wallet.advanced.recurring.label')} sub={t('wallet.advanced.recurring.sub')} />
              <Icons.chevronRight className="h-[15px] w-[15px] shrink-0 text-ink-21" />
            </button>
          }
        />

        <a href="#savings-vault" className={ROW_CLASS} data-testid="wallet-advanced-savings">
          <span className={ICON_WRAP_CLASS}>
            <Icons.stake className="h-4 w-4" />
          </span>
          <RowLabel label={t('wallet.advanced.savings.label')} sub={t('wallet.advanced.savings.sub')} />
          <Icons.chevronRight className="h-[15px] w-[15px] shrink-0 text-ink-21" />
        </a>
      </div>
    </div>
  );
}
